/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import Crime.*;
import PhysicalFeatures.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ebrue
 */
public class AdultKidnappingFrame extends javax.swing.JFrame {
    
  
    public AdultKidnappingFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        namevicadult = new javax.swing.JTextField();
        vicsurname9 = new javax.swing.JTextField();
        gendervic9 = new javax.swing.JComboBox<>();
        agevic5 = new javax.swing.JTextField();
        hwvic15 = new javax.swing.JTextField();
        vicweight = new javax.swing.JTextField();
        jLabel84 = new javax.swing.JLabel();
        lastseen = new javax.swing.JTextField();
        serialNum1 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        enmity = new javax.swing.JTextField();
        jRadioButton13 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        fppanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        financesum = new javax.swing.JComboBox<>();
        susId1 = new javax.swing.JTextField();
        namesusadult = new javax.swing.JTextField();
        sussurnameadult = new javax.swing.JTextField();
        gendersus1 = new javax.swing.JComboBox<>();
        agesus1 = new javax.swing.JTextField();
        hsus1 = new javax.swing.JTextField();
        wsus1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        where = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        fppanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        finance = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        drowcort1 = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        drowsus1 = new javax.swing.JCheckBox();
        drowalc1 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        numbers = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        addpersonbutton = new javax.swing.JButton();
        addsusbuttonadult = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        searchbutton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        susIdcomboBox = new javax.swing.JComboBox<>();
        deletesuspect2 = new javax.swing.JButton();
        vicdelname = new javax.swing.JTextField();
        deletevictim2 = new javax.swing.JButton();
        displaybutton2 = new javax.swing.JButton();
        clearbutton2 = new javax.swing.JButton();
        guiltybutton2 = new javax.swing.JButton();
        closebutton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        phonenum = new javax.swing.JTextField();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adult Kidnapping");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(null);

        namevicadult.setBackground(new java.awt.Color(255, 255, 255));
        namevicadult.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        namevicadult.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(namevicadult);
        namevicadult.setBounds(80, 110, 90, 26);

        vicsurname9.setBackground(new java.awt.Color(255, 255, 255));
        vicsurname9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        vicsurname9.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(vicsurname9);
        vicsurname9.setBounds(260, 110, 80, 26);

        gendervic9.setBackground(new java.awt.Color(255, 255, 255));
        gendervic9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        gendervic9.setForeground(new java.awt.Color(0, 0, 0));
        gendervic9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        gendervic9.setSelectedIndex(-1);
        jPanel1.add(gendervic9);
        gendervic9.setBounds(80, 170, 90, 26);

        agevic5.setBackground(new java.awt.Color(255, 255, 255));
        agevic5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        agevic5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(agevic5);
        agevic5.setBounds(260, 170, 80, 26);

        hwvic15.setBackground(new java.awt.Color(255, 255, 255));
        hwvic15.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        hwvic15.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(hwvic15);
        hwvic15.setBounds(80, 220, 90, 26);

        vicweight.setBackground(new java.awt.Color(255, 255, 255));
        vicweight.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        vicweight.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(vicweight);
        vicweight.setBounds(260, 220, 80, 26);

        jLabel84.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(255, 255, 255));
        jLabel84.setText("Where was s/he last seen?");
        jPanel1.add(jLabel84);
        jLabel84.setBounds(10, 290, 180, 24);

        lastseen.setBackground(new java.awt.Color(255, 255, 255));
        lastseen.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lastseen.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lastseen);
        lastseen.setBounds(200, 300, 130, 26);

        serialNum1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel38.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("5 people with whom s/he ");

        enmity.setBackground(new java.awt.Color(255, 255, 255));
        enmity.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        enmity.setForeground(new java.awt.Color(0, 0, 0));
        enmity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enmityActionPerformed(evt);
            }
        });

        jRadioButton13.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton13.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton13.setText("None");

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("has enmity:");

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("(separate with commas)");

        javax.swing.GroupLayout serialNum1Layout = new javax.swing.GroupLayout(serialNum1);
        serialNum1.setLayout(serialNum1Layout);
        serialNum1Layout.setHorizontalGroup(
            serialNum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serialNum1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(serialNum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addComponent(jLabel24)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(serialNum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(serialNum1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jRadioButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, serialNum1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enmity, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        serialNum1Layout.setVerticalGroup(
            serialNum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serialNum1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(serialNum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(serialNum1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jRadioButton13))
                    .addGroup(serialNum1Layout.createSequentialGroup()
                        .addGroup(serialNum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(enmity, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)))
                .addGap(64, 64, 64))
        );

        jPanel1.add(serialNum1);
        serialNum1.setBounds(10, 340, 330, 80);

        fppanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel19.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Financial situation of the person:");

        financesum.setBackground(new java.awt.Color(255, 255, 255));
        financesum.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        financesum.setForeground(new java.awt.Color(0, 0, 0));
        financesum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Poor", "Moderate", "Rich" }));
        financesum.setSelectedIndex(-1);

        javax.swing.GroupLayout fppanel1Layout = new javax.swing.GroupLayout(fppanel1);
        fppanel1.setLayout(fppanel1Layout);
        fppanel1Layout.setHorizontalGroup(
            fppanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fppanel1Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(financesum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        fppanel1Layout.setVerticalGroup(
            fppanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fppanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fppanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(financesum, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(fppanel1);
        fppanel1.setBounds(380, 340, 340, 50);

        susId1.setBackground(new java.awt.Color(255, 255, 255));
        susId1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        susId1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(susId1);
        susId1.setBounds(660, 60, 80, 26);

        namesusadult.setBackground(new java.awt.Color(255, 255, 255));
        namesusadult.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        namesusadult.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(namesusadult);
        namesusadult.setBounds(450, 110, 90, 26);

        sussurnameadult.setBackground(new java.awt.Color(255, 255, 255));
        sussurnameadult.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        sussurnameadult.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(sussurnameadult);
        sussurnameadult.setBounds(660, 110, 80, 26);

        gendersus1.setBackground(new java.awt.Color(255, 255, 255));
        gendersus1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        gendersus1.setForeground(new java.awt.Color(0, 0, 0));
        gendersus1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        gendersus1.setSelectedIndex(-1);
        jPanel1.add(gendersus1);
        gendersus1.setBounds(450, 160, 90, 26);

        agesus1.setBackground(new java.awt.Color(255, 255, 255));
        agesus1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        agesus1.setForeground(new java.awt.Color(0, 0, 0));
        agesus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agesus1ActionPerformed(evt);
            }
        });
        jPanel1.add(agesus1);
        agesus1.setBounds(660, 160, 80, 26);

        hsus1.setBackground(new java.awt.Color(255, 255, 255));
        hsus1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        hsus1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(hsus1);
        hsus1.setBounds(450, 210, 90, 26);

        wsus1.setBackground(new java.awt.Color(255, 255, 255));
        wsus1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        wsus1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(wsus1);
        wsus1.setBounds(660, 210, 80, 26);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("5 place s/he went on the day ");

        jLabel20.setForeground(new java.awt.Color(0, 0, 0));

        where.setBackground(new java.awt.Color(255, 255, 255));
        where.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        where.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("(separate with commas)");

        jLabel25.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("of the event:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(where, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)))
                .addGap(145, 145, 145))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(where, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(380, 270, 340, 60);

        fppanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel21.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Financial situation of the person:");

        finance.setBackground(new java.awt.Color(255, 255, 255));
        finance.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        finance.setForeground(new java.awt.Color(0, 0, 0));
        finance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Poor", "Moderate", "Rich" }));
        finance.setSelectedIndex(-1);

        javax.swing.GroupLayout fppanel2Layout = new javax.swing.GroupLayout(fppanel2);
        fppanel2.setLayout(fppanel2Layout);
        fppanel2Layout.setHorizontalGroup(
            fppanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fppanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finance, 0, 100, Short.MAX_VALUE))
        );
        fppanel2Layout.setVerticalGroup(
            fppanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fppanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fppanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finance, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(fppanel2);
        fppanel2.setBounds(10, 490, 330, 38);

        jLabel23.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Cortisol and Adrenaline Level");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(380, 490, 200, 26);

        drowcort1.setBackground(new java.awt.Color(255, 255, 255));
        drowcort1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        drowcort1.setForeground(new java.awt.Color(0, 0, 0));
        drowcort1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "At Reference Value", "Above the Reference Value" }));
        drowcort1.setSelectedIndex(-1);
        jPanel1.add(drowcort1);
        drowcort1.setBounds(380, 520, 215, 30);

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Found in Blood", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        drowsus1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        drowsus1.setForeground(new java.awt.Color(255, 255, 255));
        drowsus1.setText("Drug");

        drowalc1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        drowalc1.setForeground(new java.awt.Color(255, 255, 255));
        drowalc1.setText("Alcohol");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(drowsus1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(drowalc1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drowalc1)
                    .addComponent(drowsus1))
                .addGap(18, 18, 18))
        );

        jPanel1.add(jPanel9);
        jPanel9.setBounds(380, 560, 210, 60);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel22.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Does the suspect have any debt?");

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("Yes");

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setText("No");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel22)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(380, 400, 340, 34);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last 5 Call Logs :");

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));

        numbers.setBackground(new java.awt.Color(255, 255, 255));
        numbers.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        numbers.setForeground(new java.awt.Color(0, 0, 0));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("(separate with commas)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(numbers, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(numbers, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(380, 440, 340, 50);

        addpersonbutton.setBackground(new java.awt.Color(0, 0, 0));
        addpersonbutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        addpersonbutton.setForeground(new java.awt.Color(255, 255, 255));
        addpersonbutton.setText("ADD PERSON");
        addpersonbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addpersonbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpersonbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(addpersonbutton);
        addpersonbutton.setBounds(80, 630, 170, 30);

        addsusbuttonadult.setBackground(new java.awt.Color(0, 0, 0));
        addsusbuttonadult.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        addsusbuttonadult.setForeground(new java.awt.Color(255, 255, 255));
        addsusbuttonadult.setText("ADD SUSPECT");
        addsusbuttonadult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addsusbuttonadult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsusbuttonadultActionPerformed(evt);
            }
        });
        jPanel1.add(addsusbuttonadult);
        addsusbuttonadult.setBounds(460, 630, 179, 30);

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(780, 50, 190, 26);

        searchbutton2.setBackground(new java.awt.Color(0, 0, 0));
        searchbutton2.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        searchbutton2.setForeground(new java.awt.Color(255, 255, 255));
        searchbutton2.setText("SEARCH FOR SUSPECT");
        searchbutton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbutton2ActionPerformed(evt);
            }
        });
        jPanel1.add(searchbutton2);
        searchbutton2.setBounds(780, 130, 190, 42);

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Suspect ID:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(780, 90, 80, 18);

        susIdcomboBox.setBackground(new java.awt.Color(255, 255, 255));
        susIdcomboBox.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        susIdcomboBox.setForeground(new java.awt.Color(0, 0, 0));
        susIdcomboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                susIdcomboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(susIdcomboBox);
        susIdcomboBox.setBounds(890, 90, 80, 24);

        deletesuspect2.setBackground(new java.awt.Color(0, 0, 0));
        deletesuspect2.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        deletesuspect2.setForeground(new java.awt.Color(255, 255, 255));
        deletesuspect2.setText("DELETE SUSPECT");
        deletesuspect2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletesuspect2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletesuspect2ActionPerformed(evt);
            }
        });
        jPanel1.add(deletesuspect2);
        deletesuspect2.setBounds(780, 190, 190, 40);

        vicdelname.setBackground(new java.awt.Color(255, 255, 255));
        vicdelname.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        vicdelname.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(vicdelname);
        vicdelname.setBounds(900, 290, 70, 24);

        deletevictim2.setBackground(new java.awt.Color(0, 0, 0));
        deletevictim2.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        deletevictim2.setForeground(new java.awt.Color(255, 255, 255));
        deletevictim2.setText("DELETE VICTIM");
        deletevictim2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletevictim2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletevictim2ActionPerformed(evt);
            }
        });
        jPanel1.add(deletevictim2);
        deletevictim2.setBounds(780, 320, 190, 40);

        displaybutton2.setBackground(new java.awt.Color(0, 0, 0));
        displaybutton2.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        displaybutton2.setForeground(new java.awt.Color(255, 255, 255));
        displaybutton2.setText("DISPLAY CRIME INFOS");
        displaybutton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        displaybutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displaybutton2ActionPerformed(evt);
            }
        });
        jPanel1.add(displaybutton2);
        displaybutton2.setBounds(780, 410, 190, 40);

        clearbutton2.setBackground(new java.awt.Color(0, 0, 0));
        clearbutton2.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        clearbutton2.setForeground(new java.awt.Color(255, 255, 255));
        clearbutton2.setText("CLEAR FIELDS");
        clearbutton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbutton2ActionPerformed(evt);
            }
        });
        jPanel1.add(clearbutton2);
        clearbutton2.setBounds(780, 460, 190, 42);

        guiltybutton2.setBackground(new java.awt.Color(0, 0, 0));
        guiltybutton2.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        guiltybutton2.setForeground(new java.awt.Color(255, 255, 255));
        guiltybutton2.setText("FIND GUILTY");
        guiltybutton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guiltybutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiltybutton2ActionPerformed(evt);
            }
        });
        jPanel1.add(guiltybutton2);
        guiltybutton2.setBounds(780, 510, 190, 40);

        closebutton.setBackground(new java.awt.Color(0, 0, 0));
        closebutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        closebutton.setForeground(new java.awt.Color(255, 255, 255));
        closebutton.setText("Close Frame");
        closebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebuttonMouseClicked(evt);
            }
        });
        jPanel1.add(closebutton);
        closebutton.setBounds(820, 580, 130, 30);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phone Number:");

        phonenum.setBackground(new java.awt.Color(255, 255, 255));
        phonenum.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        phonenum.setForeground(new java.awt.Color(0, 0, 0));
        phonenum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(phonenum, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(phonenum, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 430, 330, 40);

        jLabel85.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(153, 0, 0));
        jLabel85.setText("ADULT KIDNAPPING");
        jPanel1.add(jLabel85);
        jLabel85.setBounds(10, 20, 200, 24);

        jLabel86.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(255, 255, 255));
        jLabel86.setText("Person's Infos");
        jPanel1.add(jLabel86);
        jLabel86.setBounds(10, 60, 140, 21);

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Suspect's Infos");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(370, 60, 170, 21);

        jLabel80.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(255, 255, 255));
        jLabel80.setText("Name:");
        jPanel1.add(jLabel80);
        jLabel80.setBounds(10, 110, 60, 18);

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Surname:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(190, 110, 70, 18);

        jLabel81.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(255, 255, 255));
        jLabel81.setText("Gender:");
        jPanel1.add(jLabel81);
        jLabel81.setBounds(10, 170, 84, 18);

        jLabel82.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(255, 255, 255));
        jLabel82.setText("Age:");
        jPanel1.add(jLabel82);
        jLabel82.setBounds(190, 170, 40, 18);

        jLabel83.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(255, 255, 255));
        jLabel83.setText("Height:");
        jPanel1.add(jLabel83);
        jLabel83.setBounds(10, 220, 60, 18);

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Weight:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(190, 220, 60, 18);

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Suspect ID:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(570, 60, 81, 18);

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Name:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(380, 110, 50, 18);

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Surname:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(570, 110, 70, 18);

        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Gender:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(380, 160, 70, 18);

        jLabel17.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Age:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(570, 160, 40, 22);

        jLabel18.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Height:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(380, 210, 60, 18);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Weight:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(570, 210, 50, 18);

        jLabel27.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Victim's Name:");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(790, 290, 100, 18);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifes/wallpaper1.png"))); // NOI18N
        jPanel1.add(jLabel28);
        jLabel28.setBounds(-50, -20, 1060, 730);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1025, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1024, 711));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
         int result = JOptionPane.showConfirmDialog(null,
            "Are you sure you want to exit the program ?\nIf you exit the program, your progress will be lost.", "Exit Confirmation: ",
            JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION)
          setDefaultCloseOperation(AdultKidnappingFrame.EXIT_ON_CLOSE);
        else if (result == JOptionPane.NO_OPTION)
          setDefaultCloseOperation(AdultKidnappingFrame.DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void enmityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enmityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enmityActionPerformed

    private void agesus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agesus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agesus1ActionPerformed

    private void addpersonbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpersonbuttonActionPerformed
        String vic_name = (String)namevicadult.getText();
        String vic_surname = (String)vicsurname9.getText();
        String gender_vic = (String)gendervic9.getSelectedItem();
        int age_vic = Integer.parseInt(agevic5.getText());
        double height_vic = Double.parseDouble(hwvic15.getText());
        double weight_vic = Double.parseDouble(vicweight.getText());
        String last_place = (String)lastseen.getText();
        String[] enmity_persons;

        String number = phonenum.getText();

        String finance_sit = (String)finance.getSelectedItem();

        double vic_strength = PhysicalFeatures.CalcMuscleStrength(age_vic, height_vic, weight_vic);

        if(jRadioButton13.isSelected()){
            String[] enmity_person = {"Not Found","","","",""};
            enmity_persons = enmity_person;
        }else{
            String[] enmity_person = new String[5];
            enmity_person = new String[5];
            String persons = enmity.getText();
            enmity_person = persons.split(",");
            enmity_persons = enmity_person;
        }

        AdultKidnapping v = new AdultKidnapping(vic_name,vic_surname,gender_vic,age_vic,height_vic,weight_vic, vic_strength, enmity_persons,number
            ,last_place, finance_sit);
        InfoClass.addVictim(v);
        jTextField1.setText("Victim added!");
    }//GEN-LAST:event_addpersonbuttonActionPerformed

    private void addsusbuttonadultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsusbuttonadultActionPerformed
        String suspect_id = susId1.getText();
        String sus_name = (String)namesusadult.getText();
        String sus_surname = (String)sussurnameadult.getText();
        String gender_sus = (String)gendersus1.getSelectedItem();
        int age_sus = Integer.parseInt(agesus1.getText());
        double height_sus = Double.parseDouble(hsus1.getText());
        double weight_sus = Double.parseDouble(wsus1.getText());
        String finance_sus = (String)financesum.getSelectedItem();
        String finance_sit = (String)finance.getSelectedItem();
        String sus_phone = (String)phonenum.getText();
        String last_place = (String)lastseen.getText();
        String number = phonenum.getText();

        String[] logcalls = new String[5];
        String numberss = numbers.getText();
        logcalls = numberss.split(",");

        String[] place = new String[5];
        String place_last = where.getText();
        place = place_last.split(",");

        susIdcomboBox.addItem(suspect_id);

        int age_vic = Integer.parseInt(agevic5.getText());
        double height_vic = Double.parseDouble(hwvic15.getText());
        double weight_vic = Double.parseDouble(vicweight.getText());

        double sus_strength = PhysicalFeatures.CalcMuscleStrength(age_sus, height_sus, weight_sus);
        double vic_strength = PhysicalFeatures.CalcMuscleStrength(age_vic, height_vic, weight_vic);
        String hormoneLevel = (String)drowcort1.getSelectedItem();

        String bloodSample;
        String bloodSamplee;

        if (drowsus1.isSelected() == true && drowalc1.isSelected() == false){
            bloodSample = "Drug found!!";
        }
        else if(drowalc1.isSelected() == true && drowsus1.isSelected() == false){
            bloodSample = "Alcohol has found!!";
        }
        else if(drowsus1.isSelected() == true && drowalc1.isSelected() == true){
            bloodSample = "Drug and Alcohol found!!";
        }
        else{
            bloodSample = "No foreign substance was found in the blood.";
        }

        if (drowsus1.isSelected() == true && drowalc1.isSelected() == false){
            bloodSamplee = "Drug";
        }
        else if(drowalc1.isSelected() == true && drowsus1.isSelected() == false){
            bloodSamplee = "Alcohol";
        }
        else if(drowsus1.isSelected() == true && drowalc1.isSelected() == true){
            bloodSamplee = "";
        }
        else{
            bloodSamplee = " ";
        }

        int rateBs = 0;
        int rateMs = 0;
        int rateHormone = 0;
        int ratePhone = 0;
        int totalRate=0;
        int rateLs = 0;
        int rateEn = 0;
        int rateFin = 0;
        int rateDebt = 0;

        if(jRadioButton13.isSelected()){
            String[] enmity_person = {"Not Found","","","",""};
            rateEn = 0;
        }else{
            String[] enmity_person = new String[5];
            String persons = enmity.getText();
            enmity_person = persons.split(",");
            rateEn = AdultKidnapping.compareEnmity(sus_name, enmity_person);
        }

        if (jRadioButton5.isSelected()){
            rateDebt = AdultKidnapping.debt();
        }
        else{
            rateDebt = 0;
        }

        rateBs = AdultKidnapping.bloodSample(bloodSamplee);
        rateMs = PhysicalFeatures.compareMuscleStrenght(vic_strength, sus_strength);
        rateHormone = AdultKidnapping.hormoneLevel(hormoneLevel);
        ratePhone = AdultKidnapping.comparePhoneNum(number, logcalls);
        rateLs = AdultKidnapping.comparePlace(last_place, place);
        rateFin = AdultKidnapping.comparefinancialSit(finance_sit, finance_sus);

        totalRate = rateBs+rateMs+rateHormone+ratePhone+rateLs+rateEn+rateFin+rateDebt;

        AdultKidnapping s = new AdultKidnapping(suspect_id,sus_name,sus_surname,gender_sus,age_sus,height_sus,
            weight_sus,sus_strength,logcalls,hormoneLevel, bloodSample,totalRate,place,finance_sus);

        InfoClass.addSuspect(s);
        jTextField1.setText("Suspect added!!");
    }//GEN-LAST:event_addsusbuttonadultActionPerformed

    private void searchbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbutton2ActionPerformed
        SearchSuspect ss = new SearchSuspect();
        ss.setVisible(true);

        if(InfoClass.suspectList.isEmpty()){
            ss.jTextArea1.append("\nThere are no suspect in the system");
        }
        else{
            String suspectId = (String)susIdcomboBox.getSelectedItem();
            Crime cd = InfoClass.searchSuspect(suspectId);
            if(cd == null)
            ss.jTextArea1.append("\nSuspect with the id " + suspectId + " is not found");
            else
            ss.jTextArea1.append(cd.toString());
        }
    }//GEN-LAST:event_searchbutton2ActionPerformed

    private void susIdcomboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_susIdcomboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_susIdcomboBoxActionPerformed

    private void deletesuspect2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletesuspect2ActionPerformed
        DisplayInfos ds = new DisplayInfos();
        ds.setVisible(true);
        InfoClass.deleteSuspect((String)susIdcomboBox.getSelectedItem());
        susIdcomboBox.removeItem(susIdcomboBox.getSelectedItem());

        ds.jTextArea3.append(InfoClass.getAllVictim());
        ds.jTextArea1.append("The id you selected has been deleted\n\n"+
            "Here is the remaining suspects\n" +InfoClass.getAllSuspect());
    }//GEN-LAST:event_deletesuspect2ActionPerformed

    private void deletevictim2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletevictim2ActionPerformed
        DisplayInfos ds = new DisplayInfos();
        ds.setVisible(true);

        InfoClass.deleteVictim(vicdelname.getText());

        ds.jTextArea3.setText("You deleted the victim.\nThere are no victims in the system."+InfoClass.getAllVictim());
        ds.jTextArea1.append(InfoClass.getAllSuspect());
    }//GEN-LAST:event_deletevictim2ActionPerformed

    private void displaybutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displaybutton2ActionPerformed
        DisplayInfos ds = new DisplayInfos();
        ds.setVisible(true);
        if(InfoClass.suspectList.isEmpty()){
            ds.jTextArea1.append("\nThere are no suspect in the system");
        }
        else{
            ds.jTextArea1.append(InfoClass.getAllSuspect());
            ds.jTextArea3.setText(InfoClass.getAllVictim());
        }
    }//GEN-LAST:event_displaybutton2ActionPerformed

    private void clearbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbutton2ActionPerformed
        susId1.setText("");
        namesusadult.setText("");
        sussurnameadult.setText("");
        gendersus1.setSelectedItem(null);
        agesus1.setText("");
        hsus1.setText("");
        wsus1.setText("");
        where.setText("");
        financesum.setSelectedItem(null);
        numbers.setText("");
        buttonGroup1.clearSelection();
        drowcort1.setSelectedItem(null);
        drowsus1.setSelected(false);
        drowalc1.setSelected(false);
    }//GEN-LAST:event_clearbutton2ActionPerformed

    private void guiltybutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiltybutton2ActionPerformed
        FindGuilty fg = new FindGuilty();
        fg.setVisible(true);
        Crime guilty = InfoClass.findGuilty();

        fg.jTextArea1.append("The max rate is: " + InfoClass.findGuilty().getTotalGuiltyRate()+ ".\nThe max rate is belongs to: "+ guilty.getSuspectId()+
            "\n\nHERE IS THE GUILTY'S INFOS: \n"+ guilty.toString());
    }//GEN-LAST:event_guiltybutton2ActionPerformed

    private void closebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebuttonMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_closebuttonMouseClicked

    private void phonenumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenumActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addpersonbutton;
    private javax.swing.JButton addsusbuttonadult;
    private javax.swing.JTextField agesus1;
    private javax.swing.JTextField agevic5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearbutton2;
    private javax.swing.JButton closebutton;
    private javax.swing.JButton deletesuspect2;
    private javax.swing.JButton deletevictim2;
    private javax.swing.JButton displaybutton2;
    private javax.swing.JCheckBox drowalc1;
    private javax.swing.JComboBox<String> drowcort1;
    private javax.swing.JCheckBox drowsus1;
    private javax.swing.JTextField enmity;
    public javax.swing.JComboBox<String> finance;
    public javax.swing.JComboBox<String> financesum;
    public javax.swing.JPanel fppanel1;
    public javax.swing.JPanel fppanel2;
    private javax.swing.JComboBox<String> gendersus1;
    private javax.swing.JComboBox<String> gendervic9;
    private javax.swing.JButton guiltybutton2;
    private javax.swing.JTextField hsus1;
    private javax.swing.JTextField hwvic15;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField lastseen;
    private javax.swing.JTextField namesusadult;
    private javax.swing.JTextField namevicadult;
    public javax.swing.JTextField numbers;
    private javax.swing.JTextField phonenum;
    private javax.swing.JButton searchbutton2;
    private javax.swing.JPanel serialNum1;
    private javax.swing.JTextField susId1;
    private javax.swing.JComboBox<String> susIdcomboBox;
    private javax.swing.JTextField sussurnameadult;
    private javax.swing.JTextField vicdelname;
    private javax.swing.JTextField vicsurname9;
    private javax.swing.JTextField vicweight;
    public javax.swing.JTextField where;
    private javax.swing.JTextField wsus1;
    // End of variables declaration//GEN-END:variables
}
