/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import Crime.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ebrue
 */
public class ChildKidnappingFrame extends javax.swing.JFrame {

    /**
     * Creates new form ChildKidnappingFrame
     */
    public ChildKidnappingFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        namevicadult2 = new javax.swing.JTextField();
        vicsurname11 = new javax.swing.JTextField();
        gendervic11 = new javax.swing.JComboBox<>();
        agevic7 = new javax.swing.JTextField();
        lastseen2 = new javax.swing.JTextField();
        serialNum3 = new javax.swing.JPanel();
        enmity2 = new javax.swing.JTextField();
        jRadioButton15 = new javax.swing.JRadioButton();
        jLabel38 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        fppanel1 = new javax.swing.JPanel();
        financesum = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        susId1 = new javax.swing.JTextField();
        namesuschild = new javax.swing.JTextField();
        sussurnamechild = new javax.swing.JTextField();
        gendersus1 = new javax.swing.JComboBox<>();
        agesus1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        where = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fppanel2 = new javax.swing.JPanel();
        finance = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        drowcort1 = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        drowsus1 = new javax.swing.JCheckBox();
        drowalc1 = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        addpersonbutton = new javax.swing.JButton();
        addsusbuttonadult = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        searchbutton2 = new javax.swing.JButton();
        susIdcomboBox = new javax.swing.JComboBox<>();
        deletesuspect2 = new javax.swing.JButton();
        vicdelname = new javax.swing.JTextField();
        deletevictim2 = new javax.swing.JButton();
        displaybutton2 = new javax.swing.JButton();
        clearbutton2 = new javax.swing.JButton();
        guiltybutton2 = new javax.swing.JButton();
        closebutton = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        where1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Child Kidnapping");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel4.setLayout(null);

        namevicadult2.setBackground(new java.awt.Color(255, 255, 255));
        namevicadult2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        namevicadult2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(namevicadult2);
        namevicadult2.setBounds(77, 72, 90, 26);

        vicsurname11.setBackground(new java.awt.Color(255, 255, 255));
        vicsurname11.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        vicsurname11.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(vicsurname11);
        vicsurname11.setBounds(250, 72, 80, 26);

        gendervic11.setBackground(new java.awt.Color(255, 255, 255));
        gendervic11.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        gendervic11.setForeground(new java.awt.Color(0, 0, 0));
        gendervic11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        gendervic11.setSelectedIndex(-1);
        jPanel4.add(gendervic11);
        gendervic11.setBounds(77, 116, 90, 26);

        agevic7.setBackground(new java.awt.Color(255, 255, 255));
        agevic7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        agevic7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(agevic7);
        agevic7.setBounds(250, 116, 80, 26);

        lastseen2.setBackground(new java.awt.Color(255, 255, 255));
        lastseen2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lastseen2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(lastseen2);
        lastseen2.setBounds(190, 180, 140, 26);

        serialNum3.setBackground(new java.awt.Color(0, 0, 0));

        enmity2.setBackground(new java.awt.Color(255, 255, 255));
        enmity2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        enmity2.setForeground(new java.awt.Color(0, 0, 0));
        enmity2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enmity2ActionPerformed(evt);
            }
        });

        jRadioButton15.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton15.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton15.setText("None");

        jLabel38.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("5 people with whom s/he ");

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("has enmity:");

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("(separate with commas)");

        javax.swing.GroupLayout serialNum3Layout = new javax.swing.GroupLayout(serialNum3);
        serialNum3.setLayout(serialNum3Layout);
        serialNum3Layout.setHorizontalGroup(
            serialNum3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serialNum3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(serialNum3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(serialNum3Layout.createSequentialGroup()
                        .addGroup(serialNum3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(serialNum3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel25)))
                        .addGap(41, 41, 41)
                        .addComponent(jRadioButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(serialNum3Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enmity2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );
        serialNum3Layout.setVerticalGroup(
            serialNum3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serialNum3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(serialNum3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enmity2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addGroup(serialNum3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(serialNum3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton15))
                    .addGroup(serialNum3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)))
                .addGap(50, 50, 50))
        );

        jPanel4.add(serialNum3);
        serialNum3.setBounds(10, 230, 330, 80);

        fppanel1.setBackground(new java.awt.Color(0, 0, 0));

        financesum.setBackground(new java.awt.Color(255, 255, 255));
        financesum.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        financesum.setForeground(new java.awt.Color(0, 0, 0));
        financesum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Poor", "Moderate", "Rich" }));
        financesum.setSelectedIndex(-1);

        jLabel19.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Financial situation of the person:");

        javax.swing.GroupLayout fppanel1Layout = new javax.swing.GroupLayout(fppanel1);
        fppanel1.setLayout(fppanel1Layout);
        fppanel1Layout.setHorizontalGroup(
            fppanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fppanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(financesum, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );
        fppanel1Layout.setVerticalGroup(
            fppanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fppanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fppanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(financesum, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel4.add(fppanel1);
        fppanel1.setBounds(400, 270, 360, 50);

        susId1.setBackground(new java.awt.Color(255, 255, 255));
        susId1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        susId1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(susId1);
        susId1.setBounds(490, 70, 100, 26);

        namesuschild.setBackground(new java.awt.Color(255, 255, 255));
        namesuschild.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        namesuschild.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(namesuschild);
        namesuschild.setBounds(490, 110, 100, 26);

        sussurnamechild.setBackground(new java.awt.Color(255, 255, 255));
        sussurnamechild.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        sussurnamechild.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(sussurnamechild);
        sussurnamechild.setBounds(680, 110, 80, 26);

        gendersus1.setBackground(new java.awt.Color(255, 255, 255));
        gendersus1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        gendersus1.setForeground(new java.awt.Color(0, 0, 0));
        gendersus1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        gendersus1.setSelectedIndex(-1);
        jPanel4.add(gendersus1);
        gendersus1.setBounds(490, 150, 100, 26);

        agesus1.setBackground(new java.awt.Color(255, 255, 255));
        agesus1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        agesus1.setForeground(new java.awt.Color(0, 0, 0));
        agesus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agesus1ActionPerformed(evt);
            }
        });
        jPanel4.add(agesus1);
        agesus1.setBounds(680, 150, 80, 26);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Where were the belongings?");

        jLabel21.setForeground(new java.awt.Color(0, 0, 0));

        where.setBackground(new java.awt.Color(255, 255, 255));
        where.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        where.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(145, 145, 145))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(21, 21, 21)
                .addComponent(where, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(where, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        jPanel4.add(jPanel5);
        jPanel5.setBounds(10, 450, 330, 40);

        fppanel2.setBackground(new java.awt.Color(0, 0, 0));

        finance.setBackground(new java.awt.Color(255, 255, 255));
        finance.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        finance.setForeground(new java.awt.Color(0, 0, 0));
        finance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Poor", "Moderate", "Rich" }));
        finance.setSelectedIndex(-1);

        jLabel26.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Financial situation of the child:");

        javax.swing.GroupLayout fppanel2Layout = new javax.swing.GroupLayout(fppanel2);
        fppanel2.setLayout(fppanel2Layout);
        fppanel2Layout.setHorizontalGroup(
            fppanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fppanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        fppanel2Layout.setVerticalGroup(
            fppanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fppanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fppanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finance, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(fppanel2);
        fppanel2.setBounds(10, 320, 330, 38);

        jLabel23.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Cortisol and Adrenaline Level:");
        jPanel4.add(jLabel23);
        jLabel23.setBounds(400, 420, 230, 26);

        drowcort1.setBackground(new java.awt.Color(255, 255, 255));
        drowcort1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        drowcort1.setForeground(new java.awt.Color(0, 0, 0));
        drowcort1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "At Reference Value", "Above the Reference Value" }));
        drowcort1.setSelectedIndex(-1);
        jPanel4.add(drowcort1);
        drowcort1.setBounds(400, 460, 240, 30);

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Found in Blood", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        drowsus1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        drowsus1.setForeground(new java.awt.Color(255, 255, 255));
        drowsus1.setText("Drug");

        drowalc1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        drowalc1.setForeground(new java.awt.Color(255, 255, 255));
        drowalc1.setText("Alcohol");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(drowsus1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(drowalc1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drowalc1)
                    .addComponent(drowsus1))
                .addGap(18, 18, 18))
        );

        jPanel4.add(jPanel9);
        jPanel9.setBounds(410, 500, 210, 60);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel24.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Has the child's belongings");

        buttonGroup6.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("Yes");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        buttonGroup6.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setText("No");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("been found?");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel6);
        jPanel6.setBounds(10, 380, 330, 50);

        addpersonbutton.setBackground(new java.awt.Color(0, 0, 0));
        addpersonbutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        addpersonbutton.setForeground(new java.awt.Color(255, 255, 255));
        addpersonbutton.setText("ADD PERSON");
        addpersonbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addpersonbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpersonbuttonActionPerformed(evt);
            }
        });
        jPanel4.add(addpersonbutton);
        addpersonbutton.setBounds(70, 570, 170, 30);

        addsusbuttonadult.setBackground(new java.awt.Color(0, 0, 0));
        addsusbuttonadult.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        addsusbuttonadult.setForeground(new java.awt.Color(255, 255, 255));
        addsusbuttonadult.setText("ADD SUSPECT");
        addsusbuttonadult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addsusbuttonadult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsusbuttonadultActionPerformed(evt);
            }
        });
        jPanel4.add(addsusbuttonadult);
        addsusbuttonadult.setBounds(480, 570, 179, 30);

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jTextField1);
        jTextField1.setBounds(810, 40, 190, 26);

        searchbutton2.setBackground(new java.awt.Color(0, 0, 0));
        searchbutton2.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        searchbutton2.setForeground(new java.awt.Color(255, 255, 255));
        searchbutton2.setText("SEARCH FOR SUSPECT");
        searchbutton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbutton2ActionPerformed(evt);
            }
        });
        jPanel4.add(searchbutton2);
        searchbutton2.setBounds(810, 110, 190, 42);

        susIdcomboBox.setBackground(new java.awt.Color(255, 255, 255));
        susIdcomboBox.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        susIdcomboBox.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(susIdcomboBox);
        susIdcomboBox.setBounds(930, 80, 72, 24);

        deletesuspect2.setBackground(new java.awt.Color(0, 0, 0));
        deletesuspect2.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        deletesuspect2.setForeground(new java.awt.Color(255, 255, 255));
        deletesuspect2.setText("DELETE SUSPECT");
        deletesuspect2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletesuspect2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletesuspect2ActionPerformed(evt);
            }
        });
        jPanel4.add(deletesuspect2);
        deletesuspect2.setBounds(810, 170, 190, 40);

        vicdelname.setBackground(new java.awt.Color(255, 255, 255));
        vicdelname.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        vicdelname.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(vicdelname);
        vicdelname.setBounds(930, 250, 70, 23);

        deletevictim2.setBackground(new java.awt.Color(0, 0, 0));
        deletevictim2.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        deletevictim2.setForeground(new java.awt.Color(255, 255, 255));
        deletevictim2.setText("DELETE VICTIM");
        deletevictim2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletevictim2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletevictim2ActionPerformed(evt);
            }
        });
        jPanel4.add(deletevictim2);
        deletevictim2.setBounds(810, 280, 190, 40);

        displaybutton2.setBackground(new java.awt.Color(0, 0, 0));
        displaybutton2.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        displaybutton2.setForeground(new java.awt.Color(255, 255, 255));
        displaybutton2.setText("DISPLAY CRIME INFOS");
        displaybutton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        displaybutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displaybutton2ActionPerformed(evt);
            }
        });
        jPanel4.add(displaybutton2);
        displaybutton2.setBounds(810, 400, 190, 40);

        clearbutton2.setBackground(new java.awt.Color(0, 0, 0));
        clearbutton2.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        clearbutton2.setForeground(new java.awt.Color(255, 255, 255));
        clearbutton2.setText("CLEAR FIELDS");
        clearbutton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbutton2ActionPerformed(evt);
            }
        });
        jPanel4.add(clearbutton2);
        clearbutton2.setBounds(810, 450, 190, 42);

        guiltybutton2.setBackground(new java.awt.Color(0, 0, 0));
        guiltybutton2.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        guiltybutton2.setForeground(new java.awt.Color(255, 255, 255));
        guiltybutton2.setText("FIND GUILTY");
        guiltybutton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guiltybutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiltybutton2ActionPerformed(evt);
            }
        });
        jPanel4.add(guiltybutton2);
        guiltybutton2.setBounds(810, 500, 190, 40);

        closebutton.setBackground(new java.awt.Color(0, 0, 0));
        closebutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        closebutton.setForeground(new java.awt.Color(255, 255, 255));
        closebutton.setText("Close Frame");
        closebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebuttonMouseClicked(evt);
            }
        });
        jPanel4.add(closebutton);
        closebutton.setBounds(850, 550, 130, 30);

        jPanel14.setBackground(new java.awt.Color(0, 0, 0));

        jLabel42.setForeground(new java.awt.Color(0, 0, 0));

        where1.setBackground(new java.awt.Color(255, 255, 255));
        where1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        where1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("5 place s/he went on the day ");

        jLabel28.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("of the event:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("(separate with commas)");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(41, 41, 41)
                        .addComponent(where1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel42)
                .addGap(145, 145, 145))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(where1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel14);
        jPanel14.setBounds(400, 190, 360, 70);

        jLabel37.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Does s/he has a criminal history?");
        jPanel4.add(jLabel37);
        jLabel37.setBounds(400, 380, 220, 18);

        buttonGroup5.add(jRadioButton16);
        jRadioButton16.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton16.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton16.setText("Yes");
        jPanel4.add(jRadioButton16);
        jRadioButton16.setBounds(640, 380, 51, 22);

        buttonGroup5.add(jRadioButton17);
        jRadioButton17.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton17.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton17.setText("No");
        jPanel4.add(jRadioButton17);
        jRadioButton17.setBounds(700, 380, 57, 22);

        buttonGroup4.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton7.setText("Yes");
        jPanel4.add(jRadioButton7);
        jRadioButton7.setBounds(640, 340, 51, 22);

        buttonGroup4.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton8.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton8.setText("No");
        jPanel4.add(jRadioButton8);
        jRadioButton8.setBounds(700, 340, 57, 22);

        jLabel85.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(153, 0, 0));
        jLabel85.setText("CHILD KIDNAPPING");
        jPanel4.add(jLabel85);
        jLabel85.setBounds(10, 10, 200, 24);

        jLabel86.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(255, 255, 255));
        jLabel86.setText("Child's Infos");
        jPanel4.add(jLabel86);
        jLabel86.setBounds(10, 40, 140, 21);

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Suspect's Infos");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(400, 40, 170, 21);

        jLabel80.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(255, 255, 255));
        jLabel80.setText("Name:");
        jPanel4.add(jLabel80);
        jLabel80.setBounds(10, 80, 60, 18);

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Surname:");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(180, 80, 70, 18);

        jLabel81.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(255, 255, 255));
        jLabel81.setText("Gender:");
        jPanel4.add(jLabel81);
        jLabel81.setBounds(10, 120, 84, 18);

        jLabel82.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(255, 255, 255));
        jLabel82.setText("Age:");
        jPanel4.add(jLabel82);
        jLabel82.setBounds(180, 120, 40, 18);

        jLabel84.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(255, 255, 255));
        jLabel84.setText("Where was s/he last seen?");
        jPanel4.add(jLabel84);
        jLabel84.setBounds(10, 180, 180, 24);

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Suspect ID:");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(400, 70, 81, 20);

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Name:");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(400, 110, 50, 18);

        jLabel20.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Gender:");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(400, 150, 70, 18);

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Surname:");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(600, 110, 70, 20);

        jLabel17.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Age:");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(600, 150, 50, 22);

        jLabel22.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Does the suspect have any debt?");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(400, 340, 220, 18);

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Suspect ID:");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(810, 80, 80, 18);

        jLabel29.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Victim's Name:");
        jPanel4.add(jLabel29);
        jLabel29.setBounds(810, 250, 100, 18);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifes/wallpaper1.png"))); // NOI18N
        jPanel4.add(jLabel2);
        jLabel2.setBounds(-40, 0, 1070, 660);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1044, 667));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
            int result = JOptionPane.showConfirmDialog(null,
            "Are you sure you want to exit the program ?\nIf you exit the program, your progress will be lost.", "Exit Confirmation: ",
            JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION)
          setDefaultCloseOperation(AdultKidnappingFrame.EXIT_ON_CLOSE);
        else if (result == JOptionPane.NO_OPTION)
          setDefaultCloseOperation(AdultKidnappingFrame.DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void enmity2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enmity2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enmity2ActionPerformed

    private void agesus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agesus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agesus1ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        jPanel5.setVisible(true);
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        jPanel5.setVisible(false);
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void addpersonbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpersonbuttonActionPerformed
        String vic_name = (String)namevicadult2.getText();
        String vic_surname = (String)vicsurname11.getText();
        String gender_vic = (String)gendervic11.getSelectedItem();
        int age_vic = Integer.parseInt(agevic7.getText());
        String last_place = (String)lastseen2.getText();
        String stuff = (String)where.getText();
        String[] enmity_persons;

        if(jRadioButton15.isSelected()){
            String[] enmity_person = {"Not Found","","","",""};
            enmity_persons = enmity_person;
        }else{
            String[] enmity_person = new String[5];
            enmity_person = new String[5];
            String persons = enmity2.getText();
            enmity_person = persons.split(",");
            enmity_persons = enmity_person;
        }

        String finance_sit = (String)finance.getSelectedItem();

        ChildKidnapping v = new ChildKidnapping(vic_name,vic_surname,gender_vic,enmity_persons,last_place, finance_sit, stuff, age_vic);
        InfoClass.addVictim(v);
        jTextField1.setText("Victim added!");
    }//GEN-LAST:event_addpersonbuttonActionPerformed

    private void addsusbuttonadultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsusbuttonadultActionPerformed
        String suspect_id = susId1.getText();
        String sus_name = (String)namesuschild.getText();
        String sus_surname = (String)sussurnamechild.getText();
        String gender_sus = (String)gendersus1.getSelectedItem();
        int age_sus = Integer.parseInt(agesus1.getText());
        String stuff = (String)where.getText();
        String[] enmity_persons;
        String finance_sus = (String)financesum.getSelectedItem();
        String finance_sit = (String)finance.getSelectedItem();

        String last_place = (String)lastseen2.getText();

        String[] place = new String[5];
        String place_last = where1.getText();
        place = place_last.split(",");

        susIdcomboBox.addItem(suspect_id);

        String hormoneLevel = (String)drowcort1.getSelectedItem();

        String bloodSample;
        String bloodSamplee;

        if (drowsus1.isSelected() == true && drowalc1.isSelected() == false){
            bloodSample = "Drug found!!";
        }
        else if(drowalc1.isSelected() == true && drowsus1.isSelected() == false){
            bloodSample = "Alcohol has found!!";
        }
        else if(drowsus1.isSelected() == true && drowalc1.isSelected() == true){
            bloodSample = "Drug and Alcohol found!!";
        }
        else{
            bloodSample = "No foreign substance was found in the blood.";
        }

        if (drowsus1.isSelected() == true && drowalc1.isSelected() == false){
            bloodSamplee = "Drug";
        }
        else if(drowalc1.isSelected() == true && drowsus1.isSelected() == false){
            bloodSamplee = "Alcohol";
        }
        else if(drowsus1.isSelected() == true && drowalc1.isSelected() == true){
            bloodSamplee = "";
        }
        else{
            bloodSamplee = " ";
        }

        int rateBs = 0;
        int rateHormone = 0;
        int totalRate=0;
        int rateLs = 0;
        int rateEn = 0;
        int rateFin = 0;
        int rateDebt = 0;
        int rateHist = 0;
        int rateSp = 0;

        if (jRadioButton5.isSelected()){
            rateDebt = ChildKidnapping.debt();
        }
        else{
            rateDebt = 0;
        }

        if (jRadioButton16.isSelected()){
            rateHist = ChildKidnapping.history();
        }
        else{
            rateHist = 0;
        }

        if(jRadioButton15.isSelected()){
            String[] enmity_person = {"Not Found","","","",""};
            enmity_persons = enmity_person;
        }else{
            String[] enmity_person = new String[5];
            enmity_person = new String[5];
            String persons = enmity2.getText();
            enmity_person = persons.split(",");
            enmity_persons = enmity_person;
            rateEn = AdultKidnapping.compareEnmity(sus_name, enmity_person);
        }

        rateBs = ChildKidnapping.bloodSample(bloodSamplee);
        rateHormone = ChildKidnapping.hormoneLevel(hormoneLevel);
        rateLs = ChildKidnapping.comparePlace(last_place, place);
        rateFin = ChildKidnapping.comparefinancialSit(finance_sit, finance_sus);
        rateSp = ChildKidnapping.compareStuffPlace(stuff, place);

        totalRate = rateBs+rateSp+rateHormone+rateHist+rateLs+rateEn+rateFin+rateDebt;

        ChildKidnapping s = new ChildKidnapping(suspect_id,sus_name,sus_surname,gender_sus,
            hormoneLevel, bloodSample,totalRate,place,finance_sus, age_sus);

        InfoClass.addSuspect(s);
        jTextField1.setText("Suspect added!!");
    }//GEN-LAST:event_addsusbuttonadultActionPerformed

    private void searchbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbutton2ActionPerformed
        SearchSuspect ss = new SearchSuspect();
        ss.setVisible(true);

        if(InfoClass.suspectList.isEmpty()){
            ss.jTextArea1.append("\nThere are no suspect in the system");
        }
        else{
            String suspectId = (String)susIdcomboBox.getSelectedItem();
            Crime cd = InfoClass.searchSuspect(suspectId);
            if(cd == null)
            ss.jTextArea1.append("\nSuspect with the id " + suspectId + " is not found");
            else
            ss.jTextArea1.append(cd.toString());
        }
    }//GEN-LAST:event_searchbutton2ActionPerformed

    private void deletesuspect2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletesuspect2ActionPerformed
        DisplayInfos ds = new DisplayInfos();
        ds.setVisible(true);
        InfoClass.deleteSuspect((String)susIdcomboBox.getSelectedItem());
        susIdcomboBox.removeItem(susIdcomboBox.getSelectedItem());

        ds.jTextArea3.append(InfoClass.getAllVictim());
        ds.jTextArea1.append("The id you selected has been deleted\n\n"+
            "Here is the remaining suspects\n" +InfoClass.getAllSuspect());
    }//GEN-LAST:event_deletesuspect2ActionPerformed

    private void deletevictim2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletevictim2ActionPerformed
        DisplayInfos ds = new DisplayInfos();
        ds.setVisible(true);

        InfoClass.deleteVictim(vicdelname.getText());

        ds.jTextArea3.setText("You deleted the victim.\nThere are no victims in the system."+InfoClass.getAllVictim());
        ds.jTextArea1.append(InfoClass.getAllSuspect());
    }//GEN-LAST:event_deletevictim2ActionPerformed

    private void displaybutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displaybutton2ActionPerformed
        DisplayInfos ds = new DisplayInfos();
        ds.setVisible(true);
        if(InfoClass.suspectList.isEmpty()){
            ds.jTextArea1.append("\nThere are no suspect in the system");
        }
        else{
            ds.jTextArea1.append(InfoClass.getAllSuspect());
            ds.jTextArea3.setText(InfoClass.getAllVictim());
        }
    }//GEN-LAST:event_displaybutton2ActionPerformed

    private void clearbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbutton2ActionPerformed
        susId1.setText("");
        namesuschild.setText("");
        sussurnamechild.setText("");
        gendersus1.setSelectedItem(null);
        agesus1.setText("");
        where.setText("");
        financesum.setSelectedItem(null);
        drowcort1.setSelectedItem(null);
        drowsus1.setSelected(false);
        drowalc1.setSelected(false);
        where1.setText("");
        buttonGroup4.clearSelection();
        buttonGroup5.clearSelection();
    }//GEN-LAST:event_clearbutton2ActionPerformed

    private void guiltybutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiltybutton2ActionPerformed
        FindGuilty fg = new FindGuilty();
        fg.setVisible(true);
        Crime guilty = InfoClass.findGuilty();

        fg.jTextArea1.append("The max rate is: " + InfoClass.findGuilty().getTotalGuiltyRate()+ ".\nThe max rate is belongs to: "+ guilty.getSuspectId()+
            "\n\nHERE IS THE GUILTY'S INFOS: \n"+ guilty.toString());
    }//GEN-LAST:event_guiltybutton2ActionPerformed

    private void closebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebuttonMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_closebuttonMouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addpersonbutton;
    private javax.swing.JButton addsusbuttonadult;
    private javax.swing.JTextField agesus1;
    private javax.swing.JTextField agevic7;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JButton clearbutton2;
    private javax.swing.JButton closebutton;
    private javax.swing.JButton deletesuspect2;
    private javax.swing.JButton deletevictim2;
    private javax.swing.JButton displaybutton2;
    private javax.swing.JCheckBox drowalc1;
    private javax.swing.JComboBox<String> drowcort1;
    private javax.swing.JCheckBox drowsus1;
    private javax.swing.JTextField enmity2;
    public javax.swing.JComboBox<String> finance;
    public javax.swing.JComboBox<String> financesum;
    public javax.swing.JPanel fppanel1;
    public javax.swing.JPanel fppanel2;
    private javax.swing.JComboBox<String> gendersus1;
    private javax.swing.JComboBox<String> gendervic11;
    private javax.swing.JButton guiltybutton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField lastseen2;
    private javax.swing.JTextField namesuschild;
    private javax.swing.JTextField namevicadult2;
    private javax.swing.JButton searchbutton2;
    private javax.swing.JPanel serialNum3;
    private javax.swing.JTextField susId1;
    private javax.swing.JComboBox<String> susIdcomboBox;
    private javax.swing.JTextField sussurnamechild;
    private javax.swing.JTextField vicdelname;
    private javax.swing.JTextField vicsurname11;
    public javax.swing.JTextField where;
    public javax.swing.JTextField where1;
    // End of variables declaration//GEN-END:variables
}
