/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;
import Crime.*;
import PhysicalFeatures.*;


import javax.swing.JOptionPane;

/**
 *
 * @author ebrue
 */
public class CuttingToolFrame extends javax.swing.JFrame {

    /**
     * Creates new form CuttingTool
     */
    public CuttingToolFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        cuttingtoolpanel1 = new javax.swing.JPanel();
        surnamevicfield5 = new javax.swing.JTextField();
        gendervic5 = new javax.swing.JComboBox<>();
        namesuscutting = new javax.swing.JTextField();
        sussurnamecutting = new javax.swing.JTextField();
        gendersus4 = new javax.swing.JComboBox<>();
        fppanel5 = new javax.swing.JPanel();
        fpmr6 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton28 = new javax.swing.JRadioButton();
        jRadioButton29 = new javax.swing.JRadioButton();
        jLabel81 = new javax.swing.JLabel();
        whl = new javax.swing.JTextField();
        drowcort4 = new javax.swing.JComboBox<>();
        jPanel18 = new javax.swing.JPanel();
        cuttingdrug = new javax.swing.JCheckBox();
        cuttingalc = new javax.swing.JCheckBox();
        agevic = new javax.swing.JTextField();
        heightvic = new javax.swing.JTextField();
        weightvic = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        numbers = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cuttingsusnum = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton30 = new javax.swing.JRadioButton();
        jRadioButton31 = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        clearbutton = new javax.swing.JButton();
        closebutton = new javax.swing.JButton();
        namevicfield6 = new javax.swing.JTextField();
        susId5 = new javax.swing.JTextField();
        addSusButton = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        addVictimButton = new javax.swing.JButton();
        displaybutton = new javax.swing.JButton();
        guiltybutton = new javax.swing.JButton();
        deletesuspectbutton = new javax.swing.JButton();
        vicdelname = new javax.swing.JTextField();
        susIdcomboBox = new javax.swing.JComboBox<>();
        deletevictim = new javax.swing.JButton();
        searchbutton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        suscrimearea = new javax.swing.JTextField();
        agesus3 = new javax.swing.JTextField();
        hsus3 = new javax.swing.JTextField();
        wsus3 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        cuttingweap = new javax.swing.JComboBox<>();
        jLabel91 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cutting Tool Death");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        cuttingtoolpanel1.setLayout(null);

        surnamevicfield5.setBackground(new java.awt.Color(255, 255, 255));
        surnamevicfield5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        surnamevicfield5.setForeground(new java.awt.Color(0, 0, 0));
        cuttingtoolpanel1.add(surnamevicfield5);
        surnamevicfield5.setBounds(130, 100, 100, 26);

        gendervic5.setBackground(new java.awt.Color(255, 255, 255));
        gendervic5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        gendervic5.setForeground(new java.awt.Color(0, 0, 0));
        gendervic5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        gendervic5.setSelectedIndex(-1);
        cuttingtoolpanel1.add(gendervic5);
        gendervic5.setBounds(130, 140, 100, 26);

        namesuscutting.setBackground(new java.awt.Color(255, 255, 255));
        namesuscutting.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        namesuscutting.setForeground(new java.awt.Color(0, 0, 0));
        cuttingtoolpanel1.add(namesuscutting);
        namesuscutting.setBounds(540, 100, 110, 26);

        sussurnamecutting.setBackground(new java.awt.Color(255, 255, 255));
        sussurnamecutting.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        sussurnamecutting.setForeground(new java.awt.Color(0, 0, 0));
        cuttingtoolpanel1.add(sussurnamecutting);
        sussurnamecutting.setBounds(540, 140, 110, 26);

        gendersus4.setBackground(new java.awt.Color(255, 255, 255));
        gendersus4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        gendersus4.setForeground(new java.awt.Color(0, 0, 0));
        gendersus4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        gendersus4.setSelectedIndex(-1);
        cuttingtoolpanel1.add(gendersus4);
        gendersus4.setBounds(540, 180, 110, 26);

        fppanel5.setBackground(new java.awt.Color(0, 0, 0));

        fpmr6.setBackground(new java.awt.Color(255, 255, 255));
        fpmr6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        fpmr6.setForeground(new java.awt.Color(0, 0, 0));
        fpmr6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "25", "50", "75", "100" }));
        fpmr6.setSelectedIndex(-1);
        fpmr6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fpmr6ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Fingerprint Match Rate %");

        javax.swing.GroupLayout fppanel5Layout = new javax.swing.GroupLayout(fppanel5);
        fppanel5.setLayout(fppanel5Layout);
        fppanel5Layout.setHorizontalGroup(
            fppanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fppanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(fpmr6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        fppanel5Layout.setVerticalGroup(
            fppanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fppanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(fpmr6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel22))
        );

        cuttingtoolpanel1.add(fppanel5);
        fppanel5.setBounds(350, 340, 310, 26);

        jPanel17.setBackground(new java.awt.Color(0, 0, 0));

        buttonGroup1.add(jRadioButton26);
        jRadioButton26.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton26.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton26.setText("Yes");
        jRadioButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton26ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton27);
        jRadioButton27.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton27.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton27.setText("No");
        jRadioButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton27ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Any fingerprint found?");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 60, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(4, 4, 4)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton26)
                    .addComponent(jRadioButton27))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cuttingtoolpanel1.add(jPanel17);
        jPanel17.setBounds(0, 370, 220, 50);

        buttonGroup2.add(jRadioButton28);
        jRadioButton28.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton28.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton28.setText("Yes");
        jRadioButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton28ActionPerformed(evt);
            }
        });
        cuttingtoolpanel1.add(jRadioButton28);
        jRadioButton28.setBounds(20, 490, 56, 22);

        buttonGroup2.add(jRadioButton29);
        jRadioButton29.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton29.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton29.setText("No");
        jRadioButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton29ActionPerformed(evt);
            }
        });
        cuttingtoolpanel1.add(jRadioButton29);
        jRadioButton29.setBounds(90, 490, 50, 22);

        jLabel81.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(255, 255, 255));
        jLabel81.setText("Surface area of the wound? W:H:L");
        cuttingtoolpanel1.add(jLabel81);
        jLabel81.setBounds(10, 600, 240, 18);

        whl.setBackground(new java.awt.Color(255, 255, 255));
        whl.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        whl.setForeground(new java.awt.Color(0, 0, 0));
        cuttingtoolpanel1.add(whl);
        whl.setBounds(20, 640, 120, 26);

        drowcort4.setBackground(new java.awt.Color(255, 255, 255));
        drowcort4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        drowcort4.setForeground(new java.awt.Color(0, 0, 0));
        drowcort4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "At Reference Value", "Above the Reference Value" }));
        drowcort4.setSelectedIndex(-1);
        cuttingtoolpanel1.add(drowcort4);
        drowcort4.setBounds(360, 670, 220, 26);

        jPanel18.setBackground(new java.awt.Color(0, 0, 0));
        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Found in Blood", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel18.setForeground(new java.awt.Color(255, 255, 255));

        cuttingdrug.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        cuttingdrug.setForeground(new java.awt.Color(255, 255, 255));
        cuttingdrug.setText("Drug");

        cuttingalc.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        cuttingalc.setForeground(new java.awt.Color(255, 255, 255));
        cuttingalc.setText("Alcohol");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cuttingdrug, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cuttingalc, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(cuttingalc)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                        .addComponent(cuttingdrug)
                        .addContainerGap())))
        );

        cuttingtoolpanel1.add(jPanel18);
        jPanel18.setBounds(350, 530, 310, 60);

        agevic.setBackground(new java.awt.Color(255, 255, 255));
        agevic.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        agevic.setForeground(new java.awt.Color(0, 0, 0));
        cuttingtoolpanel1.add(agevic);
        agevic.setBounds(130, 180, 100, 26);

        heightvic.setBackground(new java.awt.Color(255, 255, 255));
        heightvic.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        heightvic.setForeground(new java.awt.Color(0, 0, 0));
        cuttingtoolpanel1.add(heightvic);
        heightvic.setBounds(130, 220, 100, 26);

        weightvic.setBackground(new java.awt.Color(255, 255, 255));
        weightvic.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        weightvic.setForeground(new java.awt.Color(0, 0, 0));
        cuttingtoolpanel1.add(weightvic);
        weightvic.setBounds(130, 260, 100, 26);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        numbers.setBackground(new java.awt.Color(255, 255, 255));
        numbers.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        numbers.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last 5 Call Logs:");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("(separate with commas)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numbers, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel13)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numbers, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cuttingtoolpanel1.add(jPanel4);
        jPanel4.setBounds(0, 290, 240, 60);

        cuttingsusnum.setBackground(new java.awt.Color(255, 255, 255));
        cuttingsusnum.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        cuttingsusnum.setForeground(new java.awt.Color(0, 0, 0));
        cuttingtoolpanel1.add(cuttingsusnum);
        cuttingsusnum.setBounds(520, 600, 130, 26);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        buttonGroup3.add(jRadioButton30);
        jRadioButton30.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton30.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton30.setText("Yes");
        jRadioButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton30ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadioButton31);
        jRadioButton31.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton31.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton31.setText("No");
        jRadioButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton31ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Does he/she have the specified");

        jLabel24.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("crime tool?");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addComponent(jRadioButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jRadioButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        cuttingtoolpanel1.add(jPanel3);
        jPanel3.setBounds(350, 380, 310, 70);

        clearbutton.setBackground(new java.awt.Color(0, 0, 0));
        clearbutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        clearbutton.setForeground(new java.awt.Color(255, 255, 255));
        clearbutton.setText("CLEAR FIELDS");
        clearbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });
        cuttingtoolpanel1.add(clearbutton);
        clearbutton.setBounds(750, 490, 210, 42);

        closebutton.setBackground(new java.awt.Color(0, 0, 0));
        closebutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        closebutton.setForeground(new java.awt.Color(255, 255, 255));
        closebutton.setText("Close Frame");
        closebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebuttonMouseClicked(evt);
            }
        });
        cuttingtoolpanel1.add(closebutton);
        closebutton.setBounds(790, 610, 140, 30);

        namevicfield6.setBackground(new java.awt.Color(255, 255, 255));
        namevicfield6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        namevicfield6.setForeground(new java.awt.Color(0, 0, 0));
        namevicfield6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namevicfield6ActionPerformed(evt);
            }
        });
        cuttingtoolpanel1.add(namevicfield6);
        namevicfield6.setBounds(130, 60, 100, 26);

        susId5.setBackground(new java.awt.Color(255, 255, 255));
        susId5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        susId5.setForeground(new java.awt.Color(0, 0, 0));
        cuttingtoolpanel1.add(susId5);
        susId5.setBounds(540, 60, 110, 26);

        addSusButton.setBackground(new java.awt.Color(0, 0, 0));
        addSusButton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        addSusButton.setForeground(new java.awt.Color(255, 255, 255));
        addSusButton.setText("ADD SUSPECT");
        addSusButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addSusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSusButtonActionPerformed(evt);
            }
        });
        cuttingtoolpanel1.add(addSusButton);
        addSusButton.setBounds(410, 700, 130, 30);

        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(0, 0, 0));
        cuttingtoolpanel1.add(jTextField4);
        jTextField4.setBounds(750, 50, 210, 26);

        addVictimButton.setBackground(new java.awt.Color(0, 0, 0));
        addVictimButton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        addVictimButton.setForeground(new java.awt.Color(255, 255, 255));
        addVictimButton.setText("ADD VICTIM");
        addVictimButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addVictimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVictimButtonActionPerformed(evt);
            }
        });
        cuttingtoolpanel1.add(addVictimButton);
        addVictimButton.setBounds(20, 700, 130, 30);

        displaybutton.setBackground(new java.awt.Color(0, 0, 0));
        displaybutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        displaybutton.setForeground(new java.awt.Color(255, 255, 255));
        displaybutton.setText("DISPLAY CRIME INFOS");
        displaybutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        displaybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displaybuttonActionPerformed(evt);
            }
        });
        cuttingtoolpanel1.add(displaybutton);
        displaybutton.setBounds(750, 440, 210, 40);

        guiltybutton.setBackground(new java.awt.Color(0, 0, 0));
        guiltybutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        guiltybutton.setForeground(new java.awt.Color(255, 255, 255));
        guiltybutton.setText("FIND GUILTY");
        guiltybutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guiltybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiltybuttonActionPerformed(evt);
            }
        });
        cuttingtoolpanel1.add(guiltybutton);
        guiltybutton.setBounds(750, 540, 210, 40);

        deletesuspectbutton.setBackground(new java.awt.Color(0, 0, 0));
        deletesuspectbutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        deletesuspectbutton.setForeground(new java.awt.Color(255, 255, 255));
        deletesuspectbutton.setText("DELETE SUSPECT");
        deletesuspectbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletesuspectbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletesuspectbuttonActionPerformed(evt);
            }
        });
        cuttingtoolpanel1.add(deletesuspectbutton);
        deletesuspectbutton.setBounds(750, 210, 210, 40);

        vicdelname.setBackground(new java.awt.Color(255, 255, 255));
        vicdelname.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        vicdelname.setForeground(new java.awt.Color(0, 0, 0));
        cuttingtoolpanel1.add(vicdelname);
        vicdelname.setBounds(880, 300, 80, 26);

        susIdcomboBox.setBackground(new java.awt.Color(255, 255, 255));
        susIdcomboBox.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        susIdcomboBox.setForeground(new java.awt.Color(0, 0, 0));
        cuttingtoolpanel1.add(susIdcomboBox);
        susIdcomboBox.setBounds(870, 100, 80, 26);

        deletevictim.setBackground(new java.awt.Color(0, 0, 0));
        deletevictim.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        deletevictim.setForeground(new java.awt.Color(255, 255, 255));
        deletevictim.setText("DELETE VICTIM");
        deletevictim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletevictim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletevictimActionPerformed(evt);
            }
        });
        cuttingtoolpanel1.add(deletevictim);
        deletevictim.setBounds(750, 340, 210, 40);

        searchbutton.setBackground(new java.awt.Color(0, 0, 0));
        searchbutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        searchbutton.setForeground(new java.awt.Color(255, 255, 255));
        searchbutton.setText("SEARCH FOR SUSPECT");
        searchbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });
        cuttingtoolpanel1.add(searchbutton);
        searchbutton.setBounds(750, 160, 210, 42);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Enter the Surface Area of Crime Tool W:H:L");

        suscrimearea.setBackground(new java.awt.Color(255, 255, 255));
        suscrimearea.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        suscrimearea.setForeground(new java.awt.Color(0, 0, 0));
        suscrimearea.setText("0:0:0");
        suscrimearea.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(suscrimearea, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(suscrimearea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cuttingtoolpanel1.add(jPanel2);
        jPanel2.setBounds(350, 460, 310, 60);

        agesus3.setBackground(new java.awt.Color(255, 255, 255));
        agesus3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        agesus3.setForeground(new java.awt.Color(0, 0, 0));
        cuttingtoolpanel1.add(agesus3);
        agesus3.setBounds(540, 220, 110, 26);

        hsus3.setBackground(new java.awt.Color(255, 255, 255));
        hsus3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        hsus3.setForeground(new java.awt.Color(0, 0, 0));
        cuttingtoolpanel1.add(hsus3);
        hsus3.setBounds(540, 260, 110, 26);

        wsus3.setBackground(new java.awt.Color(255, 255, 255));
        wsus3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        wsus3.setForeground(new java.awt.Color(0, 0, 0));
        cuttingtoolpanel1.add(wsus3);
        wsus3.setBounds(540, 300, 110, 26);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        cuttingweap.setBackground(new java.awt.Color(255, 255, 255));
        cuttingweap.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        cuttingweap.setForeground(new java.awt.Color(0, 0, 0));
        cuttingweap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Knife", "Utility Knife", "Chisel", "Scissors", "Razor Blade" }));
        cuttingweap.setSelectedIndex(-1);

        jLabel91.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel91.setForeground(new java.awt.Color(255, 255, 255));
        jLabel91.setText("Type of Crime Weapon");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cuttingweap, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel91, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel91)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cuttingweap, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cuttingtoolpanel1.add(jPanel5);
        jPanel5.setBounds(10, 520, 210, 60);

        jLabel83.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(153, 0, 0));
        jLabel83.setText("CUTTING TOOL");
        cuttingtoolpanel1.add(jLabel83);
        jLabel83.setBounds(10, 10, 140, 24);

        jLabel86.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(255, 255, 255));
        jLabel86.setText("Victim's Infos");
        cuttingtoolpanel1.add(jLabel86);
        jLabel86.setBounds(10, 30, 140, 21);

        jLabel85.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(255, 255, 255));
        jLabel85.setText("Name:");
        cuttingtoolpanel1.add(jLabel85);
        jLabel85.setBounds(10, 60, 88, 18);

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Surname:");
        cuttingtoolpanel1.add(jLabel10);
        jLabel10.setBounds(10, 100, 70, 18);

        jLabel87.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel87.setForeground(new java.awt.Color(255, 255, 255));
        jLabel87.setText("Gender:");
        cuttingtoolpanel1.add(jLabel87);
        jLabel87.setBounds(10, 140, 84, 18);

        jLabel88.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel88.setForeground(new java.awt.Color(255, 255, 255));
        jLabel88.setText("Age:");
        cuttingtoolpanel1.add(jLabel88);
        jLabel88.setBounds(10, 180, 84, 18);

        jLabel89.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel89.setForeground(new java.awt.Color(255, 255, 255));
        jLabel89.setText("Height:");
        cuttingtoolpanel1.add(jLabel89);
        jLabel89.setBounds(10, 220, 84, 18);

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Weight:");
        cuttingtoolpanel1.add(jLabel11);
        jLabel11.setBounds(10, 260, 84, 18);

        jLabel90.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel90.setForeground(new java.awt.Color(255, 255, 255));
        jLabel90.setText("Was a crime weapon ");
        cuttingtoolpanel1.add(jLabel90);
        jLabel90.setBounds(10, 440, 140, 18);

        jLabel20.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("found at the crime scene?");
        cuttingtoolpanel1.add(jLabel20);
        jLabel20.setBounds(10, 460, 180, 15);

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Suspect's Infos");
        cuttingtoolpanel1.add(jLabel14);
        jLabel14.setBounds(360, 30, 170, 21);

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Suspect ID:");
        cuttingtoolpanel1.add(jLabel15);
        jLabel15.setBounds(360, 60, 81, 18);

        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Name:");
        cuttingtoolpanel1.add(jLabel16);
        jLabel16.setBounds(360, 100, 80, 18);

        jLabel17.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Surname:");
        cuttingtoolpanel1.add(jLabel17);
        jLabel17.setBounds(360, 140, 90, 18);

        jLabel18.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Gender:");
        cuttingtoolpanel1.add(jLabel18);
        jLabel18.setBounds(360, 180, 70, 18);

        jLabel19.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Age:");
        cuttingtoolpanel1.add(jLabel19);
        jLabel19.setBounds(360, 220, 70, 22);

        jLabel21.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Height:");
        cuttingtoolpanel1.add(jLabel21);
        jLabel21.setBounds(360, 260, 90, 18);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Weight:");
        cuttingtoolpanel1.add(jLabel5);
        jLabel5.setBounds(360, 300, 90, 18);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phone Number:");
        cuttingtoolpanel1.add(jLabel6);
        jLabel6.setBounds(360, 610, 110, 18);

        jLabel25.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Cortisol and Adrenaline Level:");
        cuttingtoolpanel1.add(jLabel25);
        jLabel25.setBounds(360, 640, 210, 26);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Suspect ID:");
        cuttingtoolpanel1.add(jLabel3);
        jLabel3.setBounds(760, 100, 79, 25);

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Victim's Name:");
        cuttingtoolpanel1.add(jLabel9);
        jLabel9.setBounds(760, 300, 100, 18);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifes/wallpaper1.png"))); // NOI18N
        cuttingtoolpanel1.add(jLabel1);
        jLabel1.setBounds(-90, -10, 1080, 860);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cuttingtoolpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cuttingtoolpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addSusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSusButtonActionPerformed
     String suspect_id = susId5.getText();
     String sus_name = (String)namesuscutting.getText();
     String sus_surname = (String)sussurnamecutting.getText();
     String gender_sus = (String)gendersus4.getSelectedItem();
     int age_sus = Integer.parseInt(agesus3.getText());
     double height_sus = Double.parseDouble(hsus3.getText());
     double weight_sus = Double.parseDouble(wsus3.getText());
     String FMR;
     String sus_phone = (String)cuttingsusnum.getText();
     String weaponType;
     String bloodSample;
     String bloodSamplee;
     String hormoneLevel = (String)drowcort4.getSelectedItem();
     susIdcomboBox.addItem(suspect_id);
     int age_vic = Integer.parseInt(agevic.getText());
     double height_vic = Double.parseDouble(heightvic.getText());
     double weight_vic = Double.parseDouble(weightvic.getText());
     String[] logcalls = new String[5];
     String numberss = numbers.getText();
     logcalls = numberss.split(",");
     
     double sus_strength = PhysicalFeatures.CalcMuscleStrength(age_sus, height_sus, weight_sus);
     double vic_strength = PhysicalFeatures.CalcMuscleStrength(age_vic, height_vic, weight_vic);
     
     
     String[] widthHeightLength = new String[3];
     String areaCrime = whl.getText();
     widthHeightLength = areaCrime.split(":");
     
     
     String[] widthHeightLength2 = new String[3];
     String areaSusCrime = suscrimearea.getText();
     widthHeightLength2 = areaSusCrime.split(":");
     double susArea = (Double.parseDouble(widthHeightLength2[0])* Double.parseDouble(widthHeightLength2[1])* 
                Double.parseDouble(widthHeightLength2[2]));
     
     double cuttingAreaCrime = (Double.parseDouble(widthHeightLength[0])* Double.parseDouble(widthHeightLength[1])* 
                Double.parseDouble(widthHeightLength[2]));
     
     double cuttingAreaSuspect;
     
     if(jRadioButton27.isSelected()){
         FMR = "Not Found";
     }
     else{
         FMR = (String)fpmr6.getSelectedItem();
     }

     if(jRadioButton30.isSelected()){
       weaponType = (String)cuttingweap.getSelectedItem();
     }
     else{
       weaponType = "Not Found";
     }

     
     if(suscrimearea.getText() == "0:0:0"){
         cuttingAreaSuspect = 0;
     }
     else{
         cuttingAreaSuspect = susArea;
     }
     
     
     if (cuttingdrug.isSelected() == true && cuttingalc.isSelected() == false){
         bloodSample = "Drug found!!";
     }
     else if(cuttingalc.isSelected() == true && cuttingdrug.isSelected() == false){
         bloodSample = "Alcohol has found!!";
      }
     else if(cuttingalc.isSelected() == true && cuttingdrug.isSelected() == true){
         bloodSample = "Drug and Alcohol found!!";
     }
     else{
        bloodSample = "No foreign substance was found in the blood.";
     }
     
     if (cuttingdrug.isSelected() == true && cuttingalc.isSelected() == false){
         bloodSamplee = "Drug";
     }
     else if(cuttingalc.isSelected() == true && cuttingdrug.isSelected() == false){
         bloodSamplee = "Alcohol";
      }
     else if(cuttingdrug.isSelected() == true && cuttingalc.isSelected() == true){
         bloodSamplee = "";
     }
     else{
        bloodSamplee = " ";
     }
     
      int rateBs = 0;
      int rateFp = 0;
      int rateMs = 0;
      int rateHormone = 0;
      int rateCrimeWeapon = 0;
      int ratePhone = 0;
      int totalRate=0;
      int rateArea=0;
      
     
      rateBs = CuttingToolDeath.bloodSample(bloodSamplee);
      rateFp = CuttingToolDeath.FingerprintRate(FMR);
      rateMs = PhysicalFeatures.compareMuscleStrenght(vic_strength, sus_strength);
      rateHormone = CuttingToolDeath.hormoneLevel(hormoneLevel);
      ratePhone = CuttingToolDeath.comparePhoneNum(sus_phone, logcalls);
      rateArea = CuttingToolDeath.compareCrimeArea(cuttingAreaCrime, cuttingAreaSuspect);
      
      if (jRadioButton28.isSelected() && jRadioButton30.isSelected()){
          rateCrimeWeapon = CuttingToolDeath.crimeWeapon();
      }
      else{
          rateCrimeWeapon = 0;
    }
      
     totalRate = rateBs+rateFp+rateMs+rateHormone+rateCrimeWeapon+ratePhone+rateArea;
     
     CuttingToolDeath s = new CuttingToolDeath(suspect_id,sus_name,sus_surname,gender_sus,FMR,age_sus,height_sus,
                                         weight_sus, weaponType,sus_strength,cuttingAreaSuspect,hormoneLevel, bloodSample,sus_phone,totalRate);

    InfoClass.addSuspect(s);
    jTextField4.setText("Suspect added!!");
    }//GEN-LAST:event_addSusButtonActionPerformed

    private void guiltybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiltybuttonActionPerformed
        FindGuilty fg = new FindGuilty();
        fg.setVisible(true);
        
         Crime guilty = InfoClass.findGuilty();
       
       fg.jTextArea1.append("The max rate is: " + InfoClass.findGuilty().getTotalGuiltyRate()+ ".\nThe max rate is belongs to: "+ guilty.getSuspectId()+
               "\n\nHERE IS THE GUILTY'S INFOS: \n"+ guilty.toString());
    
    }//GEN-LAST:event_guiltybuttonActionPerformed

    private void closebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebuttonMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_closebuttonMouseClicked

    private void displaybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displaybuttonActionPerformed
       DisplayInfos ds = new DisplayInfos();
       ds.setVisible(true);
       
         if(InfoClass.suspectList.isEmpty()){
         ds.jTextArea1.append("\nThere are no suspect in the system");
        }
        else{
        ds.jTextArea1.append(InfoClass.getAllSuspect());
        ds.jTextArea3.setText(InfoClass.getAllVictim());
         }
    }//GEN-LAST:event_displaybuttonActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
        SearchSuspect ss = new SearchSuspect();
        ss.setVisible(true);
        
        if(InfoClass.suspectList.isEmpty()){
         ss.jTextArea1.append("\nThere are no suspect in the system");
        }
        else{
         String suspectId = (String)susIdcomboBox.getSelectedItem();
         Crime cd = InfoClass.searchSuspect(suspectId);
          if(cd == null)
                ss.jTextArea1.append("\nSuspect with the id " + suspectId + " is not found");        
            else
                ss.jTextArea1.append(cd.toString());
        }
    }//GEN-LAST:event_searchbuttonActionPerformed

    private void deletevictimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletevictimActionPerformed
        DisplayInfos ds = new DisplayInfos();
        ds.setVisible(true);

        InfoClass.deleteVictim(vicdelname.getText());

        ds.jTextArea3.setText("You deleted the victim.\nThere are no victims in the system."+InfoClass.getAllVictim());
        ds.jTextArea1.append(InfoClass.getAllSuspect());
    }//GEN-LAST:event_deletevictimActionPerformed

    private void fpmr6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fpmr6ActionPerformed
   
    }//GEN-LAST:event_fpmr6ActionPerformed

    private void addVictimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVictimButtonActionPerformed
     String vic_name = (String)namevicfield6.getText();
     String vic_surname = (String)surnamevicfield5.getText();
     String gender_vic = (String)gendervic5.getSelectedItem();
     int age_vic = Integer.parseInt(agevic.getText());
     double height_vic = Double.parseDouble(heightvic.getText());
     double weight_vic = Double.parseDouble(weightvic.getText());
     double vic_strength = PhysicalFeatures.CalcMuscleStrength(age_vic, height_vic, weight_vic);
     String weaponType;
     
     
     String[] logcalls = new String[5];
     String numberss = numbers.getText();
     logcalls = numberss.split(",");
     
     String areaCrime = whl.getText();
     String[] widthHeightLength = new String[3];
     widthHeightLength = areaCrime.split(":");
     
     double cuttingAreaCrime = (Double.parseDouble(widthHeightLength[0])* Double.parseDouble(widthHeightLength[1])* 
                Double.parseDouble(widthHeightLength[2]));
     
     if(jRadioButton28.isSelected()){
       weaponType = (String)cuttingweap.getSelectedItem();
     }
     else{
       weaponType = "Not Found";
     }
     
      CuttingToolDeath v = new CuttingToolDeath(vic_name,vic_surname,gender_vic,logcalls,age_vic,weaponType,
              height_vic,weight_vic, vic_strength,cuttingAreaCrime);
      InfoClass.addVictim(v);
      jTextField4.setText("Victim added!");
     
     
    }//GEN-LAST:event_addVictimButtonActionPerformed

    private void deletesuspectbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletesuspectbuttonActionPerformed
        DisplayInfos ds = new DisplayInfos();
         ds.setVisible(true);
            InfoClass.deleteSuspect((String)susIdcomboBox.getSelectedItem());
            susIdcomboBox.removeItem(susIdcomboBox.getSelectedItem());
            
            ds.jTextArea3.append(InfoClass.getAllVictim());
            ds.jTextArea1.append("The id you selected has been deleted\n\n"+
                    "Here is the remaining suspects\n" +InfoClass.getAllSuspect());
    }//GEN-LAST:event_deletesuspectbuttonActionPerformed

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        susId5.setText("");
        namesuscutting.setText("");
        sussurnamecutting.setText("");
        gendersus4.setSelectedItem(null);
        agesus3.setText("");
        hsus3.setText("");
        wsus3.setText("");
        fpmr6.setSelectedItem(null);
        suscrimearea.setText("0:0:0");
        cuttingsusnum.setText("");
        drowcort4.setSelectedItem(null);
        cuttingdrug.setSelected(false);
        cuttingalc.setSelected(false);
        buttonGroup3.clearSelection();
    }//GEN-LAST:event_clearbuttonActionPerformed

    private void jRadioButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton26ActionPerformed
      fppanel5.setVisible(true);
    }//GEN-LAST:event_jRadioButton26ActionPerformed

    private void jRadioButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton27ActionPerformed
       fppanel5.setVisible(false);
    }//GEN-LAST:event_jRadioButton27ActionPerformed

    private void jRadioButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton28ActionPerformed
       jPanel5.setVisible(true);
       jPanel3.setVisible(true);
       jPanel2.setVisible(true);
    }//GEN-LAST:event_jRadioButton28ActionPerformed

    private void jRadioButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton29ActionPerformed
       jPanel5.setVisible(false);
       jPanel2.setVisible(false);
       jPanel3.setVisible(false);
    }//GEN-LAST:event_jRadioButton29ActionPerformed

    private void jRadioButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton30ActionPerformed
        jPanel2.setVisible(true);
    }//GEN-LAST:event_jRadioButton30ActionPerformed

    private void jRadioButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton31ActionPerformed
       jPanel2.setVisible(false);
    }//GEN-LAST:event_jRadioButton31ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       int result = JOptionPane.showConfirmDialog(null,
            "Are you sure you want to exit the program ?\nIf you exit the program, your progress will be lost.", "Exit Confirmation: ",
            JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION)
          setDefaultCloseOperation(DrowningFrame.EXIT_ON_CLOSE);
        else if (result == JOptionPane.NO_OPTION)
          setDefaultCloseOperation(DrowningFrame.DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void namevicfield6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namevicfield6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namevicfield6ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSusButton;
    private javax.swing.JButton addVictimButton;
    private javax.swing.JTextField agesus3;
    private javax.swing.JTextField agevic;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton clearbutton;
    private javax.swing.JButton closebutton;
    private javax.swing.JCheckBox cuttingalc;
    private javax.swing.JCheckBox cuttingdrug;
    private javax.swing.JTextField cuttingsusnum;
    private javax.swing.JPanel cuttingtoolpanel1;
    private javax.swing.JComboBox<String> cuttingweap;
    private javax.swing.JButton deletesuspectbutton;
    private javax.swing.JButton deletevictim;
    private javax.swing.JButton displaybutton;
    private javax.swing.JComboBox<String> drowcort4;
    private javax.swing.JComboBox<String> fpmr6;
    private javax.swing.JPanel fppanel5;
    private javax.swing.JComboBox<String> gendersus4;
    private javax.swing.JComboBox<String> gendervic5;
    private javax.swing.JButton guiltybutton;
    private javax.swing.JTextField heightvic;
    private javax.swing.JTextField hsus3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField namesuscutting;
    private javax.swing.JTextField namevicfield6;
    private javax.swing.JTextField numbers;
    private javax.swing.JButton searchbutton;
    private javax.swing.JTextField surnamevicfield5;
    private javax.swing.JTextField susId5;
    private javax.swing.JComboBox<String> susIdcomboBox;
    private javax.swing.JTextField suscrimearea;
    private javax.swing.JTextField sussurnamecutting;
    private javax.swing.JTextField vicdelname;
    private javax.swing.JTextField weightvic;
    private javax.swing.JTextField whl;
    private javax.swing.JTextField wsus3;
    // End of variables declaration//GEN-END:variables
}
