/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import javax.swing.JOptionPane;

/**
 *
 * @author ebrue
 */
public class DeathFrame extends javax.swing.JFrame {

  DrowningFrame dw;
  CuttingToolFrame ct;
  WithAGunFrame wg;
  HeadDamageFrame hd;
    
    public DeathFrame() {
        initComponents();
        this.setSize(565,345);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel70 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        drowningbutton = new javax.swing.JRadioButton();
        withagunbutton = new javax.swing.JRadioButton();
        headdamagebutton = new javax.swing.JRadioButton();
        cuttingtoolbutton = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        drowningbutton1 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Murder Crimes");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel70.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(204, 0, 0));
        jLabel70.setText("Criminal Detection System");
        getContentPane().add(jLabel70);
        jLabel70.setBounds(40, 20, 390, 33);

        jLabel6.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Type of Death");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 50, 140, 24);

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("(Make Your Selection and Press Enter)");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 80, 300, 22);

        buttonGroup1.add(drowningbutton);
        drowningbutton.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        drowningbutton.setForeground(new java.awt.Color(255, 255, 255));
        drowningbutton.setText("DROWNING");
        drowningbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        drowningbutton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                drowningbuttonKeyPressed(evt);
            }
        });
        getContentPane().add(drowningbutton);
        drowningbutton.setBounds(40, 120, 140, 28);

        buttonGroup1.add(withagunbutton);
        withagunbutton.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        withagunbutton.setForeground(new java.awt.Color(255, 255, 255));
        withagunbutton.setText("WITH A GUN");
        withagunbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        withagunbutton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                withagunbuttonKeyPressed(evt);
            }
        });
        getContentPane().add(withagunbutton);
        withagunbutton.setBounds(40, 150, 140, 28);

        buttonGroup1.add(headdamagebutton);
        headdamagebutton.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        headdamagebutton.setForeground(new java.awt.Color(255, 255, 255));
        headdamagebutton.setText("HEAD DAMAGE");
        headdamagebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        headdamagebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                headdamagebuttonActionPerformed(evt);
            }
        });
        headdamagebutton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                headdamagebuttonKeyPressed(evt);
            }
        });
        getContentPane().add(headdamagebutton);
        headdamagebutton.setBounds(40, 210, 180, 28);

        buttonGroup1.add(cuttingtoolbutton);
        cuttingtoolbutton.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        cuttingtoolbutton.setForeground(new java.awt.Color(255, 255, 255));
        cuttingtoolbutton.setText("CUTTING TOOL");
        cuttingtoolbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cuttingtoolbutton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cuttingtoolbuttonKeyPressed(evt);
            }
        });
        getContentPane().add(cuttingtoolbutton);
        cuttingtoolbutton.setBounds(40, 180, 150, 28);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Close Frame");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(410, 270, 140, 25);

        buttonGroup1.add(drowningbutton1);
        drowningbutton1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        drowningbutton1.setForeground(new java.awt.Color(255, 255, 255));
        drowningbutton1.setText("DROWNING");
        drowningbutton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                drowningbutton1KeyPressed(evt);
            }
        });
        getContentPane().add(drowningbutton1);
        drowningbutton1.setBounds(40, 120, 140, 28);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifes/glassbullet.gif"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 560, 340);

        setSize(new java.awt.Dimension(573, 337));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void withagunbuttonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_withagunbuttonKeyPressed
        wg = new WithAGunFrame();
        wg.setVisible(true);
    }//GEN-LAST:event_withagunbuttonKeyPressed

    private void headdamagebuttonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_headdamagebuttonKeyPressed
         hd = new HeadDamageFrame();
        hd.setVisible(true);
    }//GEN-LAST:event_headdamagebuttonKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int result = JOptionPane.showConfirmDialog(null,
            "Are you sure you want to exit the program ?\nIf you exit the program, your progress will be lost.", "Exit Confirmation: ",
            JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION)
          setDefaultCloseOperation(DrowningFrame.EXIT_ON_CLOSE);
        else if (result == JOptionPane.NO_OPTION)
          setDefaultCloseOperation(DrowningFrame.DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void headdamagebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headdamagebuttonActionPerformed

                
    }//GEN-LAST:event_headdamagebuttonActionPerformed

    private void drowningbutton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_drowningbutton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_drowningbutton1KeyPressed

    private void cuttingtoolbuttonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cuttingtoolbuttonKeyPressed
        ct = new CuttingToolFrame();
        ct.setVisible(true);
    }//GEN-LAST:event_cuttingtoolbuttonKeyPressed

    private void drowningbuttonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_drowningbuttonKeyPressed
        dw = new DrowningFrame();
        dw.setVisible(true);
    }//GEN-LAST:event_drowningbuttonKeyPressed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cuttingtoolbutton;
    private javax.swing.JRadioButton drowningbutton;
    private javax.swing.JRadioButton drowningbutton1;
    private javax.swing.JRadioButton headdamagebutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JRadioButton withagunbutton;
    // End of variables declaration//GEN-END:variables
}
