/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;
import Crime.*;
import PhysicalFeatures.*;
import javax.swing.JOptionPane;

public class DrowningFrame extends javax.swing.JFrame {

   
    public DrowningFrame() {
        initComponents();
        this.setSize(908,707 );
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        drowningpanel6 = new javax.swing.JPanel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        namevicdrow = new javax.swing.JTextField();
        jLabel81 = new javax.swing.JLabel();
        gendervic7 = new javax.swing.JComboBox<>();
        jLabel82 = new javax.swing.JLabel();
        agevic5 = new javax.swing.JTextField();
        jLabel83 = new javax.swing.JLabel();
        hwvic5 = new javax.swing.JTextField();
        jLabel84 = new javax.swing.JLabel();
        drowningpanel7 = new javax.swing.JPanel();
        jLabel85 = new javax.swing.JLabel();
        drowweap4 = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        susId1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        namesusdrowning = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        gendersus1 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        agesus1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        hsus1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        drowsus1 = new javax.swing.JCheckBox();
        drowalc1 = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        drowcort1 = new javax.swing.JComboBox<>();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        fppanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        fpmr1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        wsus1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        numbers = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        drowsusnum = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        vicweight = new javax.swing.JTextField();
        addsusbutton = new javax.swing.JButton();
        searchbutton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        susIdcomboBox = new javax.swing.JComboBox<>();
        deletevictim = new javax.swing.JButton();
        displaybutton = new javax.swing.JButton();
        clearbutton = new javax.swing.JButton();
        guiltybutton = new javax.swing.JButton();
        closebutton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        vicsurname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sussurnamedrow = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        addvicbutton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        deletesuspect = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        vicdelname = new javax.swing.JTextField();
        jLabel86 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Drowning Death");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(null);

        drowningpanel6.setLayout(null);

        jLabel79.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(153, 0, 0));
        jLabel79.setText("DROWNING");
        drowningpanel6.add(jLabel79);
        jLabel79.setBounds(10, 10, 140, 24);

        jLabel80.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(255, 255, 255));
        jLabel80.setText("Name:");
        drowningpanel6.add(jLabel80);
        jLabel80.setBounds(10, 60, 88, 18);

        namevicdrow.setBackground(new java.awt.Color(255, 255, 255));
        namevicdrow.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        namevicdrow.setForeground(new java.awt.Color(0, 0, 0));
        drowningpanel6.add(namevicdrow);
        namevicdrow.setBounds(110, 60, 90, 26);

        jLabel81.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(255, 255, 255));
        jLabel81.setText("Gender:");
        drowningpanel6.add(jLabel81);
        jLabel81.setBounds(10, 140, 84, 18);

        gendervic7.setBackground(new java.awt.Color(255, 255, 255));
        gendervic7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        gendervic7.setForeground(new java.awt.Color(0, 0, 0));
        gendervic7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        gendervic7.setSelectedIndex(-1);
        drowningpanel6.add(gendervic7);
        gendervic7.setBounds(110, 140, 90, 26);

        jLabel82.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(255, 255, 255));
        jLabel82.setText("Age:");
        drowningpanel6.add(jLabel82);
        jLabel82.setBounds(10, 180, 84, 18);

        agevic5.setBackground(new java.awt.Color(255, 255, 255));
        agevic5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        agevic5.setForeground(new java.awt.Color(0, 0, 0));
        drowningpanel6.add(agevic5);
        agevic5.setBounds(110, 180, 90, 26);

        jLabel83.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(255, 255, 255));
        jLabel83.setText("Height:");
        drowningpanel6.add(jLabel83);
        jLabel83.setBounds(10, 220, 84, 18);

        hwvic5.setBackground(new java.awt.Color(255, 255, 255));
        hwvic5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        hwvic5.setForeground(new java.awt.Color(0, 0, 0));
        drowningpanel6.add(hwvic5);
        hwvic5.setBounds(110, 220, 90, 26);

        jLabel84.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(255, 255, 255));
        jLabel84.setText("Was a crime weapon ");
        drowningpanel6.add(jLabel84);
        jLabel84.setBounds(20, 450, 140, 18);

        drowningpanel7.setBackground(new java.awt.Color(0, 0, 0));

        jLabel85.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(255, 255, 255));
        jLabel85.setText("Type of Crime Weapon");

        drowweap4.setBackground(new java.awt.Color(255, 255, 255));
        drowweap4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        drowweap4.setForeground(new java.awt.Color(0, 0, 0));
        drowweap4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wire", "Plastic", "Belt", "Fabric", "Rope", "With Hand" }));
        drowweap4.setSelectedIndex(-1);

        javax.swing.GroupLayout drowningpanel7Layout = new javax.swing.GroupLayout(drowningpanel7);
        drowningpanel7.setLayout(drowningpanel7Layout);
        drowningpanel7Layout.setHorizontalGroup(
            drowningpanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drowningpanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(drowningpanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(drowningpanel7Layout.createSequentialGroup()
                        .addComponent(drowweap4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 104, Short.MAX_VALUE))
                    .addComponent(jLabel85, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        drowningpanel7Layout.setVerticalGroup(
            drowningpanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drowningpanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel85)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drowweap4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        drowningpanel6.add(drowningpanel7);
        drowningpanel7.setBounds(20, 540, 220, 62);

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Yes");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        drowningpanel6.add(jRadioButton1);
        jRadioButton1.setBounds(20, 500, 56, 22);

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Suspect's Infos");
        drowningpanel6.add(jLabel12);
        jLabel12.setBounds(350, 30, 170, 21);

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Suspect ID:");
        drowningpanel6.add(jLabel14);
        jLabel14.setBounds(350, 60, 81, 18);

        susId1.setBackground(new java.awt.Color(255, 255, 255));
        susId1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        susId1.setForeground(new java.awt.Color(0, 0, 0));
        drowningpanel6.add(susId1);
        susId1.setBounds(450, 60, 100, 26);

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Name:");
        drowningpanel6.add(jLabel15);
        jLabel15.setBounds(350, 100, 123, 18);

        namesusdrowning.setBackground(new java.awt.Color(255, 255, 255));
        namesusdrowning.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        namesusdrowning.setForeground(new java.awt.Color(0, 0, 0));
        drowningpanel6.add(namesusdrowning);
        namesusdrowning.setBounds(450, 100, 100, 26);

        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Gender:");
        drowningpanel6.add(jLabel16);
        jLabel16.setBounds(350, 180, 70, 18);

        gendersus1.setBackground(new java.awt.Color(255, 255, 255));
        gendersus1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        gendersus1.setForeground(new java.awt.Color(0, 0, 0));
        gendersus1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        gendersus1.setSelectedIndex(-1);
        drowningpanel6.add(gendersus1);
        gendersus1.setBounds(450, 180, 100, 26);

        jLabel17.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Age:");
        drowningpanel6.add(jLabel17);
        jLabel17.setBounds(350, 220, 70, 22);

        agesus1.setBackground(new java.awt.Color(255, 255, 255));
        agesus1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        agesus1.setForeground(new java.awt.Color(0, 0, 0));
        agesus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agesus1ActionPerformed(evt);
            }
        });
        drowningpanel6.add(agesus1);
        agesus1.setBounds(450, 220, 100, 26);

        jLabel18.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Height:");
        drowningpanel6.add(jLabel18);
        jLabel18.setBounds(350, 260, 123, 18);

        hsus1.setBackground(new java.awt.Color(255, 255, 255));
        hsus1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        hsus1.setForeground(new java.awt.Color(0, 0, 0));
        drowningpanel6.add(hsus1);
        hsus1.setBounds(450, 260, 100, 26);

        jLabel20.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("found at the crime scene?");
        drowningpanel6.add(jLabel20);
        jLabel20.setBounds(20, 470, 180, 15);

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Found in Blood", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel9.setForeground(new java.awt.Color(255, 255, 255));

        drowsus1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        drowsus1.setForeground(new java.awt.Color(255, 255, 255));
        drowsus1.setText("Drug");

        drowalc1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        drowalc1.setForeground(new java.awt.Color(255, 255, 255));
        drowalc1.setText("Alcohol");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(drowsus1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(drowalc1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drowalc1)
                    .addComponent(drowsus1))
                .addGap(18, 18, 18))
        );

        drowningpanel6.add(jPanel9);
        jPanel9.setBounds(340, 460, 240, 60);

        jLabel23.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Cortisol and Adrenaline Level:");
        drowningpanel6.add(jLabel23);
        jLabel23.setBounds(340, 560, 210, 26);

        drowcort1.setBackground(new java.awt.Color(255, 255, 255));
        drowcort1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        drowcort1.setForeground(new java.awt.Color(0, 0, 0));
        drowcort1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "At Reference Value", "Above the Reference Value" }));
        drowcort1.setSelectedIndex(-1);
        drowningpanel6.add(drowcort1);
        drowcort1.setBounds(340, 590, 230, 24);

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("No");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        drowningpanel6.add(jRadioButton2);
        jRadioButton2.setBounds(120, 500, 50, 22);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("No");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        drowningpanel6.add(jRadioButton4);
        jRadioButton4.setBounds(110, 410, 51, 22);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Yes");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        drowningpanel6.add(jRadioButton3);
        jRadioButton3.setBounds(30, 410, 62, 22);

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Any fingerprint found?");
        drowningpanel6.add(jLabel11);
        jLabel11.setBounds(20, 380, 160, 18);

        fppanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel19.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Fingerprint Match Rate %");

        fpmr1.setBackground(new java.awt.Color(255, 255, 255));
        fpmr1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        fpmr1.setForeground(new java.awt.Color(0, 0, 0));
        fpmr1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "25", "50", "75", "100" }));
        fpmr1.setSelectedIndex(-1);

        javax.swing.GroupLayout fppanel1Layout = new javax.swing.GroupLayout(fppanel1);
        fppanel1.setLayout(fppanel1Layout);
        fppanel1Layout.setHorizontalGroup(
            fppanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fppanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fpmr1, 0, 59, Short.MAX_VALUE))
        );
        fppanel1Layout.setVerticalGroup(
            fppanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fppanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fppanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fpmr1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        drowningpanel6.add(fppanel1);
        fppanel1.setBounds(340, 340, 240, 38);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Weight:");
        drowningpanel6.add(jLabel4);
        jLabel4.setBounds(350, 300, 90, 18);

        wsus1.setBackground(new java.awt.Color(255, 255, 255));
        wsus1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        wsus1.setForeground(new java.awt.Color(0, 0, 0));
        drowningpanel6.add(wsus1);
        wsus1.setBounds(450, 300, 100, 26);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last 5 Call Logs:");

        numbers.setBackground(new java.awt.Color(255, 255, 255));
        numbers.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        numbers.setForeground(new java.awt.Color(0, 0, 0));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("(separate with commas)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numbers)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel13)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numbers, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        drowningpanel6.add(jPanel4);
        jPanel4.setBounds(10, 310, 230, 60);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone Number:");
        drowningpanel6.add(jLabel5);
        jLabel5.setBounds(340, 530, 110, 18);

        drowsusnum.setBackground(new java.awt.Color(255, 255, 255));
        drowsusnum.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        drowsusnum.setForeground(new java.awt.Color(0, 0, 0));
        drowsusnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drowsusnumActionPerformed(evt);
            }
        });
        drowningpanel6.add(drowsusnum);
        drowsusnum.setBounds(460, 530, 110, 26);

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Weight:");
        drowningpanel6.add(jLabel7);
        jLabel7.setBounds(10, 260, 84, 18);

        vicweight.setBackground(new java.awt.Color(255, 255, 255));
        vicweight.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        vicweight.setForeground(new java.awt.Color(0, 0, 0));
        drowningpanel6.add(vicweight);
        vicweight.setBounds(110, 260, 90, 26);

        addsusbutton.setBackground(new java.awt.Color(0, 0, 0));
        addsusbutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        addsusbutton.setForeground(new java.awt.Color(255, 255, 255));
        addsusbutton.setText("ADD SUSPECT");
        addsusbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addsusbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsusbuttonActionPerformed(evt);
            }
        });
        drowningpanel6.add(addsusbutton);
        addsusbutton.setBounds(390, 630, 130, 30);

        searchbutton.setBackground(new java.awt.Color(0, 0, 0));
        searchbutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        searchbutton.setForeground(new java.awt.Color(255, 255, 255));
        searchbutton.setText("SEARCH FOR SUSPECT");
        searchbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });
        drowningpanel6.add(searchbutton);
        searchbutton.setBounds(670, 150, 190, 42);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Suspect ID:");
        drowningpanel6.add(jLabel3);
        jLabel3.setBounds(670, 110, 79, 25);

        susIdcomboBox.setBackground(new java.awt.Color(255, 255, 255));
        susIdcomboBox.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        susIdcomboBox.setForeground(new java.awt.Color(0, 0, 0));
        drowningpanel6.add(susIdcomboBox);
        susIdcomboBox.setBounds(790, 110, 72, 26);

        deletevictim.setBackground(new java.awt.Color(0, 0, 0));
        deletevictim.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        deletevictim.setForeground(new java.awt.Color(255, 255, 255));
        deletevictim.setText("DELETE VICTIM");
        deletevictim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletevictim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletevictimActionPerformed(evt);
            }
        });
        drowningpanel6.add(deletevictim);
        deletevictim.setBounds(670, 350, 190, 40);

        displaybutton.setBackground(new java.awt.Color(0, 0, 0));
        displaybutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        displaybutton.setForeground(new java.awt.Color(255, 255, 255));
        displaybutton.setText("DISPLAY CRIME INFOS");
        displaybutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        displaybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displaybuttonActionPerformed(evt);
            }
        });
        drowningpanel6.add(displaybutton);
        displaybutton.setBounds(670, 460, 190, 40);

        clearbutton.setBackground(new java.awt.Color(0, 0, 0));
        clearbutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        clearbutton.setForeground(new java.awt.Color(255, 255, 255));
        clearbutton.setText("CLEAR FIELDS");
        clearbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });
        drowningpanel6.add(clearbutton);
        clearbutton.setBounds(670, 510, 190, 42);

        guiltybutton.setBackground(new java.awt.Color(0, 0, 0));
        guiltybutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        guiltybutton.setForeground(new java.awt.Color(255, 255, 255));
        guiltybutton.setText("FIND GUILTY");
        guiltybutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guiltybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiltybuttonActionPerformed(evt);
            }
        });
        drowningpanel6.add(guiltybutton);
        guiltybutton.setBounds(670, 560, 190, 40);

        closebutton.setBackground(new java.awt.Color(0, 0, 0));
        closebutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        closebutton.setForeground(new java.awt.Color(255, 255, 255));
        closebutton.setText("Close Frame");
        closebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebuttonMouseClicked(evt);
            }
        });
        closebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebuttonActionPerformed(evt);
            }
        });
        drowningpanel6.add(closebutton);
        closebutton.setBounds(700, 620, 130, 30);

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Surname:");
        drowningpanel6.add(jLabel8);
        jLabel8.setBounds(10, 100, 70, 18);

        vicsurname.setBackground(new java.awt.Color(255, 255, 255));
        vicsurname.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        vicsurname.setForeground(new java.awt.Color(0, 0, 0));
        drowningpanel6.add(vicsurname);
        vicsurname.setBounds(110, 100, 90, 26);

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Surname:");
        drowningpanel6.add(jLabel9);
        jLabel9.setBounds(350, 140, 90, 18);

        sussurnamedrow.setBackground(new java.awt.Color(255, 255, 255));
        sussurnamedrow.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        drowningpanel6.add(sussurnamedrow);
        sussurnamedrow.setBounds(450, 140, 100, 26);

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        drowningpanel6.add(jTextField1);
        jTextField1.setBounds(670, 60, 190, 26);

        addvicbutton.setBackground(new java.awt.Color(0, 0, 0));
        addvicbutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        addvicbutton.setForeground(new java.awt.Color(255, 255, 255));
        addvicbutton.setText("ADD VICTIM");
        addvicbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addvicbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addvicbuttonActionPerformed(evt);
            }
        });
        drowningpanel6.add(addvicbutton);
        addvicbutton.setBounds(40, 630, 120, 30);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel21.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Does he/she have the specified");

        buttonGroup3.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("Yes");

        buttonGroup3.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setText("No");

        jLabel22.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("crime tool?");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jRadioButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6))
                .addContainerGap())
        );

        drowningpanel6.add(jPanel2);
        jPanel2.setBounds(340, 380, 240, 76);

        deletesuspect.setBackground(new java.awt.Color(0, 0, 0));
        deletesuspect.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        deletesuspect.setForeground(new java.awt.Color(255, 255, 255));
        deletesuspect.setText("DELETE SUSPECT");
        deletesuspect.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletesuspect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletesuspectActionPerformed(evt);
            }
        });
        drowningpanel6.add(deletesuspect);
        deletesuspect.setBounds(670, 200, 190, 40);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Victim's Name:");
        drowningpanel6.add(jLabel6);
        jLabel6.setBounds(670, 310, 100, 18);

        vicdelname.setBackground(new java.awt.Color(255, 255, 255));
        vicdelname.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        vicdelname.setForeground(new java.awt.Color(0, 0, 0));
        vicdelname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vicdelnameActionPerformed(evt);
            }
        });
        drowningpanel6.add(vicdelname);
        vicdelname.setBounds(790, 310, 70, 26);

        jLabel86.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(255, 255, 255));
        jLabel86.setText("Victim's Infos");
        drowningpanel6.add(jLabel86);
        jLabel86.setBounds(10, 30, 140, 21);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifes/wallpaper1.png"))); // NOI18N
        drowningpanel6.add(jLabel1);
        jLabel1.setBounds(-100, 0, 1010, 680);

        jPanel1.add(drowningpanel6);
        drowningpanel6.setBounds(0, 0, 900, 670);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        int result = JOptionPane.showConfirmDialog(null,
            "Are you sure you want to exit the program ?\nIf you exit the program, your progress will be lost.", "Exit Confirmation: ",
            JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION)
          setDefaultCloseOperation(DrowningFrame.EXIT_ON_CLOSE);
        else if (result == JOptionPane.NO_OPTION)
          setDefaultCloseOperation(DrowningFrame.DO_NOTHING_ON_CLOSE);
   
    }//GEN-LAST:event_formWindowClosing

    private void deletesuspectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletesuspectActionPerformed
        DisplayInfos ds = new DisplayInfos();
        ds.setVisible(true);
        InfoClass.deleteSuspect((String)susIdcomboBox.getSelectedItem());
        susIdcomboBox.removeItem(susIdcomboBox.getSelectedItem());

        ds.jTextArea3.append(InfoClass.getAllVictim());
        ds.jTextArea1.append("The id you selected has been deleted\n\n"+
            "Here is the remaining suspects\n" +InfoClass.getAllSuspect());

    }//GEN-LAST:event_deletesuspectActionPerformed

    private void addvicbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addvicbuttonActionPerformed
        String vic_name = (String)namevicdrow.getText();
        String vic_surname = (String)vicsurname.getText();
        String gender_vic = (String)gendervic7.getSelectedItem();
        int age_vic = Integer.parseInt(agevic5.getText());
        double height_vic = Double.parseDouble(hwvic5.getText());
        double weight_vic = Double.parseDouble(vicweight.getText());
        double vic_strength = PhysicalFeatures.CalcMuscleStrength(age_vic, height_vic, weight_vic);
        String weaponType;

        String[] logcalls = new String[5];
        String numberss = numbers.getText();
        logcalls = numberss.split(",");

        if(jRadioButton1.isSelected()){
            weaponType = (String)drowweap4.getSelectedItem();
        }
        else{
            weaponType = "Not Found";
        }

        DrowningDeath v = new DrowningDeath(vic_name,vic_surname,gender_vic,logcalls,age_vic,weaponType,height_vic,weight_vic, vic_strength);
        InfoClass.addVictim(v);
        jTextField1.setText("Victim added!");
    }//GEN-LAST:event_addvicbuttonActionPerformed

    private void closebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebuttonMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_closebuttonMouseClicked

    private void guiltybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiltybuttonActionPerformed
        FindGuilty fg = new FindGuilty();
        fg.setVisible(true);
        Crime guilty = InfoClass.findGuilty();

        fg.jTextArea1.append("The max rate is: " + InfoClass.findGuilty().getTotalGuiltyRate()+ ".\nThe max rate is belongs to: "+ guilty.getSuspectId()+
            "\n\nHERE IS THE GUILTY'S INFOS: \n"+ guilty.toString());

    }//GEN-LAST:event_guiltybuttonActionPerformed

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        susId1.setText("");
        namesusdrowning.setText("");
        sussurnamedrow.setText("");
        gendersus1.setSelectedItem(null);
        agesus1.setText("");
        hsus1.setText("");
        wsus1.setText("");
        fpmr1.setSelectedItem(null);
        drowsusnum.setText("");
        drowcort1.setSelectedItem(null);
        drowsus1.setSelected(false);
        drowalc1.setSelected(false);
        buttonGroup3.clearSelection();

    }//GEN-LAST:event_clearbuttonActionPerformed

    private void displaybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displaybuttonActionPerformed
        DisplayInfos ds = new DisplayInfos();
        ds.setVisible(true);
        if(InfoClass.suspectList.isEmpty()){
            ds.jTextArea1.append("\nThere are no suspect in the system");
        }
        else{
            ds.jTextArea1.append(InfoClass.getAllSuspect());
            ds.jTextArea3.setText(InfoClass.getAllVictim());
        }
    }//GEN-LAST:event_displaybuttonActionPerformed

    private void deletevictimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletevictimActionPerformed
        DisplayInfos ds = new DisplayInfos();
        ds.setVisible(true);

        InfoClass.deleteVictim(vicdelname.getText());

        ds.jTextArea3.setText("You deleted the victim.\nThere are no victims in the system.\n"+InfoClass.getAllVictim());
        ds.jTextArea1.append(InfoClass.getAllSuspect());
    }//GEN-LAST:event_deletevictimActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
        SearchSuspect ss = new SearchSuspect();
        ss.setVisible(true);

        if(InfoClass.suspectList.isEmpty()){
            ss.jTextArea1.append("\nThere are no suspect in the system");
        }
        else{
            String suspectId = (String)susIdcomboBox.getSelectedItem();
            Crime cd = InfoClass.searchSuspect(suspectId);
            if(cd == null)
            ss.jTextArea1.append("\nSuspect with the id " + suspectId + " is not found");
            else
            ss.jTextArea1.append(cd.toString());
        }
    }//GEN-LAST:event_searchbuttonActionPerformed

    private void addsusbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsusbuttonActionPerformed
        String suspect_id = susId1.getText();
        String sus_name = (String)namesusdrowning.getText();
        String sus_surname = (String)sussurnamedrow.getText();
        String gender_sus = (String)gendersus1.getSelectedItem();
        int age_sus = Integer.parseInt(agesus1.getText());
        double height_sus = Double.parseDouble(hsus1.getText());
        double weight_sus = Double.parseDouble(wsus1.getText());
        String FMR;
        String sus_phone = (String)drowsusnum.getText();
        String weaponType;
        String bloodSample;
        String bloodSamplee;
        String hormoneLevel = (String)drowcort1.getSelectedItem();
        susIdcomboBox.addItem(suspect_id);
        int age_vic = Integer.parseInt(agevic5.getText());
        double height_vic = Double.parseDouble(hwvic5.getText());
        double weight_vic = Double.parseDouble(vicweight.getText());
        String[] logcalls = new String[5];
        String numberss = numbers.getText();
        logcalls = numberss.split(",");
        double sus_strength = PhysicalFeatures.CalcMuscleStrength(age_sus, height_sus, weight_sus);
        double vic_strength = PhysicalFeatures.CalcMuscleStrength(age_vic, height_vic, weight_vic);

        if(jRadioButton4.isSelected()){
            FMR = "Not Found";
        }
        else{
            FMR = (String)fpmr1.getSelectedItem();
        }

        if(jRadioButton5.isSelected()){
            weaponType = (String)drowweap4.getSelectedItem();
        }
        else{
            weaponType = "Not Found";
        }

        if (drowsus1.isSelected() == true && drowalc1.isSelected() == false){
            bloodSample = "Drug found!!";
        }
        else if(drowalc1.isSelected() == true && drowsus1.isSelected() == false){
            bloodSample = "Alcohol has found!!";
        }
        else if(drowsus1.isSelected() == true && drowalc1.isSelected() == true){
            bloodSample = "Drug and Alcohol found!!";
        }
        else{
            bloodSample = "No foreign substance was found in the blood.";
        }

        if (drowsus1.isSelected() == true && drowalc1.isSelected() == false){
            bloodSamplee = "Drug";
        }
        else if(drowalc1.isSelected() == true && drowsus1.isSelected() == false){
            bloodSamplee = "Alcohol";
        }
        else if(drowsus1.isSelected() == true && drowalc1.isSelected() == true){
            bloodSamplee = "";
        }
        else{
            bloodSamplee = " ";
        }

        int rateBs = 0;
        int rateFp = 0;
        int rateMs = 0;
        int rateHormone = 0;
        int rateCrimeWeapon = 0;
        int ratePhone = 0;
        int totalRate=0;

        rateBs = DrowningDeath.bloodSample(bloodSamplee);
        rateFp = DrowningDeath.FingerprintRate(FMR);
        rateMs = PhysicalFeatures.compareMuscleStrenght(vic_strength, sus_strength);
        rateHormone = DrowningDeath.hormoneLevel(hormoneLevel);
        ratePhone = DrowningDeath.comparePhoneNum(sus_phone, logcalls);

        if (jRadioButton5.isSelected()){
            rateCrimeWeapon = DrowningDeath.crimeWeapon();
        }
        else{
            rateCrimeWeapon = 0;
        }

        totalRate = rateBs+rateFp+rateMs+rateHormone+rateCrimeWeapon+ratePhone;

        DrowningDeath s = new DrowningDeath(suspect_id,sus_name,sus_surname,gender_sus,FMR,age_sus,height_sus,
            weight_sus, weaponType,sus_strength,hormoneLevel, bloodSample,sus_phone,totalRate);

        InfoClass.addSuspect(s);
        jTextField1.setText("Suspect added!!");

    }//GEN-LAST:event_addsusbuttonActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        fppanel1.setVisible(true);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        fppanel1.setVisible(false);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        drowningpanel7.setVisible(false);
        jPanel2.setVisible(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void agesus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agesus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agesus1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        drowningpanel7.setVisible(true);
        jPanel2.setVisible(true);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void drowsusnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drowsusnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drowsusnumActionPerformed

    private void vicdelnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vicdelnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vicdelnameActionPerformed

    private void closebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addsusbutton;
    private javax.swing.JButton addvicbutton;
    private javax.swing.JTextField agesus1;
    private javax.swing.JTextField agevic5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton clearbutton;
    private javax.swing.JButton closebutton;
    private javax.swing.JButton deletesuspect;
    private javax.swing.JButton deletevictim;
    private javax.swing.JButton displaybutton;
    private javax.swing.JCheckBox drowalc1;
    private javax.swing.JComboBox<String> drowcort1;
    private javax.swing.JPanel drowningpanel6;
    private javax.swing.JPanel drowningpanel7;
    private javax.swing.JCheckBox drowsus1;
    private javax.swing.JTextField drowsusnum;
    private javax.swing.JComboBox<String> drowweap4;
    private javax.swing.Box.Filler filler1;
    public javax.swing.JComboBox<String> fpmr1;
    public javax.swing.JPanel fppanel1;
    private javax.swing.JComboBox<String> gendersus1;
    private javax.swing.JComboBox<String> gendervic7;
    private javax.swing.JButton guiltybutton;
    private javax.swing.JTextField hsus1;
    private javax.swing.JTextField hwvic5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel9;
    private static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField namesusdrowning;
    private javax.swing.JTextField namevicdrow;
    public javax.swing.JTextField numbers;
    private javax.swing.JButton searchbutton;
    private javax.swing.JTextField susId1;
    private javax.swing.JComboBox<String> susIdcomboBox;
    private javax.swing.JTextField sussurnamedrow;
    private javax.swing.JTextField vicdelname;
    private javax.swing.JTextField vicsurname;
    private javax.swing.JTextField vicweight;
    private javax.swing.JTextField wsus1;
    // End of variables declaration//GEN-END:variables
}
