/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;
import Crime.*;
import javax.swing.JOptionPane;
/**
 *
 * @author ebrue
 */
public class HeadDamageFrame extends javax.swing.JFrame {

    /**
     * Creates new form HeadDamageFrame
     */
    public HeadDamageFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        cuttingtoolpanel5 = new javax.swing.JPanel();
        surnamevicfield9 = new javax.swing.JTextField();
        gendervic9 = new javax.swing.JComboBox<>();
        namesushead = new javax.swing.JTextField();
        sussurnamehead = new javax.swing.JTextField();
        gendersus8 = new javax.swing.JComboBox<>();
        fppanel9 = new javax.swing.JPanel();
        fpmr10 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jRadioButton28 = new javax.swing.JRadioButton();
        jRadioButton29 = new javax.swing.JRadioButton();
        headcort4 = new javax.swing.JComboBox<>();
        jPanel18 = new javax.swing.JPanel();
        headdrug = new javax.swing.JCheckBox();
        headalc = new javax.swing.JCheckBox();
        agevic = new javax.swing.JTextField();
        weightvic = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        numbers = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        headsusnum = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton30 = new javax.swing.JRadioButton();
        jRadioButton31 = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        clearbutton = new javax.swing.JButton();
        closebutton = new javax.swing.JButton();
        namevicfield6 = new javax.swing.JTextField();
        susId5 = new javax.swing.JTextField();
        addSusButton = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        addVictimButton = new javax.swing.JButton();
        displaybutton = new javax.swing.JButton();
        guiltybutton = new javax.swing.JButton();
        deletesuspectbutton = new javax.swing.JButton();
        vicdelname = new javax.swing.JTextField();
        susIdcomboBox = new javax.swing.JComboBox<>();
        deletevictim = new javax.swing.JButton();
        searchbutton = new javax.swing.JButton();
        agesus3 = new javax.swing.JTextField();
        wsus3 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        headweap = new javax.swing.JComboBox<>();
        jLabel85 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        susweaponweight = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        crimeweapweight = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel79 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jRadioButton27 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        jLabel84 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Head Damage Death");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        cuttingtoolpanel5.setBackground(new java.awt.Color(0, 0, 0));
        cuttingtoolpanel5.setLayout(null);

        surnamevicfield9.setBackground(new java.awt.Color(255, 255, 255));
        surnamevicfield9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        surnamevicfield9.setForeground(new java.awt.Color(0, 0, 0));
        cuttingtoolpanel5.add(surnamevicfield9);
        surnamevicfield9.setBounds(140, 90, 100, 26);

        gendervic9.setBackground(new java.awt.Color(255, 255, 255));
        gendervic9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        gendervic9.setForeground(new java.awt.Color(0, 0, 0));
        gendervic9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        gendervic9.setSelectedIndex(-1);
        cuttingtoolpanel5.add(gendervic9);
        gendervic9.setBounds(140, 130, 100, 26);

        namesushead.setBackground(new java.awt.Color(255, 255, 255));
        namesushead.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        namesushead.setForeground(new java.awt.Color(0, 0, 0));
        cuttingtoolpanel5.add(namesushead);
        namesushead.setBounds(540, 90, 110, 26);

        sussurnamehead.setBackground(new java.awt.Color(255, 255, 255));
        sussurnamehead.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        sussurnamehead.setForeground(new java.awt.Color(0, 0, 0));
        cuttingtoolpanel5.add(sussurnamehead);
        sussurnamehead.setBounds(540, 130, 110, 26);

        gendersus8.setBackground(new java.awt.Color(255, 255, 255));
        gendersus8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        gendersus8.setForeground(new java.awt.Color(0, 0, 0));
        gendersus8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        gendersus8.setSelectedIndex(-1);
        cuttingtoolpanel5.add(gendersus8);
        gendersus8.setBounds(540, 170, 110, 26);

        fppanel9.setBackground(new java.awt.Color(0, 0, 0));

        fpmr10.setBackground(new java.awt.Color(255, 255, 255));
        fpmr10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        fpmr10.setForeground(new java.awt.Color(0, 0, 0));
        fpmr10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "25", "50", "75", "100" }));
        fpmr10.setSelectedIndex(-1);
        fpmr10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fpmr10ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Fingerprint Match Rate %");

        javax.swing.GroupLayout fppanel9Layout = new javax.swing.GroupLayout(fppanel9);
        fppanel9.setLayout(fppanel9Layout);
        fppanel9Layout.setHorizontalGroup(
            fppanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fppanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fpmr10, 0, 107, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        fppanel9Layout.setVerticalGroup(
            fppanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fppanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(fpmr10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel21))
        );

        cuttingtoolpanel5.add(fppanel9);
        fppanel9.setBounds(360, 300, 300, 30);

        buttonGroup3.add(jRadioButton28);
        jRadioButton28.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton28.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton28.setText("Yes");
        jRadioButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton28ActionPerformed(evt);
            }
        });
        cuttingtoolpanel5.add(jRadioButton28);
        jRadioButton28.setBounds(20, 520, 56, 22);

        buttonGroup3.add(jRadioButton29);
        jRadioButton29.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton29.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton29.setText("No");
        jRadioButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton29ActionPerformed(evt);
            }
        });
        cuttingtoolpanel5.add(jRadioButton29);
        jRadioButton29.setBounds(100, 520, 50, 22);

        headcort4.setBackground(new java.awt.Color(255, 255, 255));
        headcort4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        headcort4.setForeground(new java.awt.Color(0, 0, 0));
        headcort4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "At Reference Value", "Above the Reference Value" }));
        headcort4.setSelectedIndex(-1);
        cuttingtoolpanel5.add(headcort4);
        headcort4.setBounds(360, 650, 230, 26);

        jPanel18.setBackground(new java.awt.Color(0, 0, 0));
        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Found in Blood", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel18.setForeground(new java.awt.Color(255, 255, 255));

        headdrug.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        headdrug.setForeground(new java.awt.Color(255, 255, 255));
        headdrug.setText("Drug");

        headalc.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        headalc.setForeground(new java.awt.Color(255, 255, 255));
        headalc.setText("Alcohol");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headdrug, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(headalc, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(headalc)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                        .addComponent(headdrug)
                        .addContainerGap())))
        );

        cuttingtoolpanel5.add(jPanel18);
        jPanel18.setBounds(360, 490, 300, 60);

        agevic.setBackground(new java.awt.Color(255, 255, 255));
        agevic.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        agevic.setForeground(new java.awt.Color(0, 0, 0));
        cuttingtoolpanel5.add(agevic);
        agevic.setBounds(140, 170, 100, 26);

        weightvic.setBackground(new java.awt.Color(255, 255, 255));
        weightvic.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        weightvic.setForeground(new java.awt.Color(0, 0, 0));
        cuttingtoolpanel5.add(weightvic);
        weightvic.setBounds(140, 210, 100, 26);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        numbers.setBackground(new java.awt.Color(255, 255, 255));
        numbers.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        numbers.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last 5 Call Logs:");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("(separate with commas)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numbers, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel13)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numbers, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cuttingtoolpanel5.add(jPanel4);
        jPanel4.setBounds(10, 270, 270, 60);

        headsusnum.setBackground(new java.awt.Color(255, 255, 255));
        headsusnum.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        headsusnum.setForeground(new java.awt.Color(0, 0, 0));
        cuttingtoolpanel5.add(headsusnum);
        headsusnum.setBounds(520, 570, 140, 26);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        buttonGroup1.add(jRadioButton30);
        jRadioButton30.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton30.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton30.setText("Yes");
        jRadioButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton30ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton31);
        jRadioButton31.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton31.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton31.setText("No");
        jRadioButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton31ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Does he/she have the specified");

        jLabel23.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("crime tool?");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(69, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jRadioButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton30)
                    .addComponent(jRadioButton31))
                .addContainerGap())
        );

        cuttingtoolpanel5.add(jPanel3);
        jPanel3.setBounds(360, 340, 300, 70);

        clearbutton.setBackground(new java.awt.Color(0, 0, 0));
        clearbutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        clearbutton.setForeground(new java.awt.Color(255, 255, 255));
        clearbutton.setText("CLEAR FIELDS");
        clearbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });
        cuttingtoolpanel5.add(clearbutton);
        clearbutton.setBounds(760, 510, 190, 42);

        closebutton.setBackground(new java.awt.Color(0, 0, 0));
        closebutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        closebutton.setForeground(new java.awt.Color(255, 255, 255));
        closebutton.setText("Close Frame");
        closebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebuttonMouseClicked(evt);
            }
        });
        cuttingtoolpanel5.add(closebutton);
        closebutton.setBounds(790, 630, 140, 30);

        namevicfield6.setBackground(new java.awt.Color(255, 255, 255));
        namevicfield6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        namevicfield6.setForeground(new java.awt.Color(0, 0, 0));
        cuttingtoolpanel5.add(namevicfield6);
        namevicfield6.setBounds(140, 50, 100, 26);

        susId5.setBackground(new java.awt.Color(255, 255, 255));
        susId5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        susId5.setForeground(new java.awt.Color(0, 0, 0));
        cuttingtoolpanel5.add(susId5);
        susId5.setBounds(540, 50, 110, 26);

        addSusButton.setBackground(new java.awt.Color(0, 0, 0));
        addSusButton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        addSusButton.setForeground(new java.awt.Color(255, 255, 255));
        addSusButton.setText("ADD SUSPECT");
        addSusButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addSusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSusButtonActionPerformed(evt);
            }
        });
        cuttingtoolpanel5.add(addSusButton);
        addSusButton.setBounds(420, 710, 130, 30);

        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(0, 0, 0));
        cuttingtoolpanel5.add(jTextField4);
        jTextField4.setBounds(760, 50, 190, 26);

        addVictimButton.setBackground(new java.awt.Color(0, 0, 0));
        addVictimButton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        addVictimButton.setForeground(new java.awt.Color(255, 255, 255));
        addVictimButton.setText("ADD VICTIM");
        addVictimButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addVictimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVictimButtonActionPerformed(evt);
            }
        });
        cuttingtoolpanel5.add(addVictimButton);
        addVictimButton.setBounds(60, 710, 130, 30);

        displaybutton.setBackground(new java.awt.Color(0, 0, 0));
        displaybutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        displaybutton.setForeground(new java.awt.Color(255, 255, 255));
        displaybutton.setText("DISPLAY CRIME INFOS");
        displaybutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        displaybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displaybuttonActionPerformed(evt);
            }
        });
        cuttingtoolpanel5.add(displaybutton);
        displaybutton.setBounds(760, 460, 190, 40);

        guiltybutton.setBackground(new java.awt.Color(0, 0, 0));
        guiltybutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        guiltybutton.setForeground(new java.awt.Color(255, 255, 255));
        guiltybutton.setText("FIND GUILTY");
        guiltybutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guiltybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiltybuttonActionPerformed(evt);
            }
        });
        cuttingtoolpanel5.add(guiltybutton);
        guiltybutton.setBounds(760, 560, 190, 40);

        deletesuspectbutton.setBackground(new java.awt.Color(0, 0, 0));
        deletesuspectbutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        deletesuspectbutton.setForeground(new java.awt.Color(255, 255, 255));
        deletesuspectbutton.setText("DELETE SUSPECT");
        deletesuspectbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletesuspectbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletesuspectbuttonActionPerformed(evt);
            }
        });
        cuttingtoolpanel5.add(deletesuspectbutton);
        deletesuspectbutton.setBounds(760, 180, 190, 40);

        vicdelname.setBackground(new java.awt.Color(255, 255, 255));
        vicdelname.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        vicdelname.setForeground(new java.awt.Color(0, 0, 0));
        cuttingtoolpanel5.add(vicdelname);
        vicdelname.setBounds(870, 290, 80, 26);

        susIdcomboBox.setBackground(new java.awt.Color(255, 255, 255));
        susIdcomboBox.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        susIdcomboBox.setForeground(new java.awt.Color(0, 0, 0));
        cuttingtoolpanel5.add(susIdcomboBox);
        susIdcomboBox.setBounds(870, 90, 80, 26);

        deletevictim.setBackground(new java.awt.Color(0, 0, 0));
        deletevictim.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        deletevictim.setForeground(new java.awt.Color(255, 255, 255));
        deletevictim.setText("DELETE VICTIM");
        deletevictim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletevictim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletevictimActionPerformed(evt);
            }
        });
        cuttingtoolpanel5.add(deletevictim);
        deletevictim.setBounds(760, 330, 190, 40);

        searchbutton.setBackground(new java.awt.Color(0, 0, 0));
        searchbutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        searchbutton.setForeground(new java.awt.Color(255, 255, 255));
        searchbutton.setText("SEARCH FOR SUSPECT");
        searchbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });
        cuttingtoolpanel5.add(searchbutton);
        searchbutton.setBounds(760, 130, 190, 42);

        agesus3.setBackground(new java.awt.Color(255, 255, 255));
        agesus3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        agesus3.setForeground(new java.awt.Color(0, 0, 0));
        cuttingtoolpanel5.add(agesus3);
        agesus3.setBounds(540, 210, 110, 26);

        wsus3.setBackground(new java.awt.Color(255, 255, 255));
        wsus3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        wsus3.setForeground(new java.awt.Color(0, 0, 0));
        cuttingtoolpanel5.add(wsus3);
        wsus3.setBounds(540, 250, 110, 26);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        headweap.setBackground(new java.awt.Color(255, 255, 255));
        headweap.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        headweap.setForeground(new java.awt.Color(0, 0, 0));
        headweap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Glass Bottle", "Metal Bottle", "Iron Stick", "Baseball Bat", "Golf Bat", "Vase", "Marble", "Wood", "Ohter" }));
        headweap.setSelectedIndex(-1);
        headweap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                headweapActionPerformed(evt);
            }
        });

        jLabel85.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(255, 255, 255));
        jLabel85.setText("Type of Crime Weapon");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(headweap, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 148, Short.MAX_VALUE))
                    .addComponent(jLabel85, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel85)
                .addGap(4, 4, 4)
                .addComponent(headweap, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cuttingtoolpanel5.add(jPanel5);
        jPanel5.setBounds(10, 560, 280, 60);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Crime Weapon's Weight");

        susweaponweight.setBackground(new java.awt.Color(255, 255, 255));
        susweaponweight.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        susweaponweight.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(susweaponweight, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(susweaponweight, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cuttingtoolpanel5.add(jPanel1);
        jPanel1.setBounds(360, 420, 300, 60);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Enter Crime Weapon's Weight");

        crimeweapweight.setBackground(new java.awt.Color(255, 255, 255));
        crimeweapweight.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        crimeweapweight.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(crimeweapweight, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crimeweapweight, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cuttingtoolpanel5.add(jPanel2);
        jPanel2.setBounds(10, 630, 280, 60);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Damage Size:");

        jSlider1.setBackground(new java.awt.Color(0, 0, 0));
        jSlider1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jSlider1.setForeground(new java.awt.Color(255, 255, 255));
        jSlider1.setMajorTickSpacing(1);
        jSlider1.setMaximum(10);
        jSlider1.setMinorTickSpacing(1);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setValue(0);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(15, 15, 15))
        );

        cuttingtoolpanel5.add(jPanel6);
        jPanel6.setBounds(10, 340, 270, 50);

        jLabel79.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(153, 0, 0));
        jLabel79.setText("HEAD DAMAGE");
        cuttingtoolpanel5.add(jLabel79);
        jLabel79.setBounds(10, 10, 140, 24);

        jLabel86.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(255, 255, 255));
        jLabel86.setText("Victim's Infos");
        cuttingtoolpanel5.add(jLabel86);
        jLabel86.setBounds(10, 30, 140, 21);

        jLabel80.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(255, 255, 255));
        jLabel80.setText("Name:");
        cuttingtoolpanel5.add(jLabel80);
        jLabel80.setBounds(10, 60, 88, 18);

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Surname:");
        cuttingtoolpanel5.add(jLabel11);
        jLabel11.setBounds(10, 100, 70, 18);

        jLabel81.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(255, 255, 255));
        jLabel81.setText("Gender:");
        cuttingtoolpanel5.add(jLabel81);
        jLabel81.setBounds(10, 140, 84, 18);

        jLabel82.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(255, 255, 255));
        jLabel82.setText("Age:");
        cuttingtoolpanel5.add(jLabel82);
        jLabel82.setBounds(10, 180, 84, 18);

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Weight:");
        cuttingtoolpanel5.add(jLabel12);
        jLabel12.setBounds(10, 220, 84, 18);

        jLabel107.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel107.setForeground(new java.awt.Color(255, 255, 255));
        jLabel107.setText("Any fingerprint found?");
        cuttingtoolpanel5.add(jLabel107);
        jLabel107.setBounds(20, 400, 168, 18);

        buttonGroup2.add(jRadioButton27);
        jRadioButton27.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton27.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton27.setText("No");
        jRadioButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton27ActionPerformed(evt);
            }
        });
        cuttingtoolpanel5.add(jRadioButton27);
        jRadioButton27.setBounds(100, 430, 51, 20);

        buttonGroup2.add(jRadioButton26);
        jRadioButton26.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton26.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton26.setText("Yes");
        jRadioButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton26ActionPerformed(evt);
            }
        });
        cuttingtoolpanel5.add(jRadioButton26);
        jRadioButton26.setBounds(20, 430, 62, 20);

        jLabel84.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(255, 255, 255));
        jLabel84.setText("Was a crime weapon ");
        cuttingtoolpanel5.add(jLabel84);
        jLabel84.setBounds(20, 480, 140, 18);

        jLabel20.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("found at the crime scene?");
        cuttingtoolpanel5.add(jLabel20);
        jLabel20.setBounds(20, 500, 180, 15);

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Suspect's Infos");
        cuttingtoolpanel5.add(jLabel14);
        jLabel14.setBounds(370, 30, 170, 21);

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Suspect ID:");
        cuttingtoolpanel5.add(jLabel15);
        jLabel15.setBounds(370, 60, 81, 18);

        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Name:");
        cuttingtoolpanel5.add(jLabel16);
        jLabel16.setBounds(370, 100, 90, 18);

        jLabel17.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Surname:");
        cuttingtoolpanel5.add(jLabel17);
        jLabel17.setBounds(370, 140, 90, 18);

        jLabel18.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Gender:");
        cuttingtoolpanel5.add(jLabel18);
        jLabel18.setBounds(370, 180, 70, 18);

        jLabel19.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Age:");
        cuttingtoolpanel5.add(jLabel19);
        jLabel19.setBounds(370, 220, 70, 22);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Weight:");
        cuttingtoolpanel5.add(jLabel5);
        jLabel5.setBounds(370, 260, 90, 18);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phone Number:");
        cuttingtoolpanel5.add(jLabel6);
        jLabel6.setBounds(360, 570, 110, 18);

        jLabel24.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Cortisol and Adrenaline Level:");
        cuttingtoolpanel5.add(jLabel24);
        jLabel24.setBounds(360, 610, 210, 26);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Suspect ID:");
        cuttingtoolpanel5.add(jLabel4);
        jLabel4.setBounds(760, 90, 79, 25);

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Victim's Name:");
        cuttingtoolpanel5.add(jLabel9);
        jLabel9.setBounds(760, 290, 100, 18);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifes/wallpaper1.png"))); // NOI18N
        cuttingtoolpanel5.add(jLabel1);
        jLabel1.setBounds(-83, 0, 1060, 780);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cuttingtoolpanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cuttingtoolpanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        setSize(new java.awt.Dimension(992, 783));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fpmr10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fpmr10ActionPerformed

    }//GEN-LAST:event_fpmr10ActionPerformed

    private void jRadioButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton26ActionPerformed
        fppanel9.setVisible(true);
    }//GEN-LAST:event_jRadioButton26ActionPerformed

    private void jRadioButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton27ActionPerformed
        fppanel9.setVisible(false);
    }//GEN-LAST:event_jRadioButton27ActionPerformed

    private void jRadioButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton28ActionPerformed
        jPanel5.setVisible(true);
        jPanel2.setVisible(true);
        jPanel3.setVisible(true);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_jRadioButton28ActionPerformed

    private void jRadioButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton29ActionPerformed
        jPanel5.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_jRadioButton29ActionPerformed

    private void jRadioButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton30ActionPerformed
        jPanel1.setVisible(true);
    }//GEN-LAST:event_jRadioButton30ActionPerformed

    private void jRadioButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton31ActionPerformed
        jPanel1.setVisible(false);
    }//GEN-LAST:event_jRadioButton31ActionPerformed

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        susId5.setText("");
        namesushead.setText("");
        sussurnamehead.setText("");
        gendersus8.setSelectedItem(null);
        agesus3.setText("");
        wsus3.setText("");
        susweaponweight.setText("");
        fpmr10.setSelectedItem(null);
        headsusnum.setText("");
        headcort4.setSelectedItem(null);
        headdrug.setSelected(false);
        headalc.setSelected(false);
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_clearbuttonActionPerformed

    private void closebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebuttonMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_closebuttonMouseClicked

    private void addSusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSusButtonActionPerformed
        String suspect_id = susId5.getText();
        String sus_name = (String)namesushead.getText();
        String sus_surname = (String)sussurnamehead.getText();
        String gender_sus = (String)gendersus8.getSelectedItem();
        int age_sus = Integer.parseInt(agesus3.getText());
        double weight_sus = Double.parseDouble(wsus3.getText());
        double susweaponWeight;
        double crimeweaponWeight;
        String FMR;
        String sus_phone = (String)headsusnum.getText();
        String weaponType;
        String bloodSample;
        String bloodSamplee;
        String hormoneLevel = (String)headcort4.getSelectedItem();
        susIdcomboBox.addItem(suspect_id);
        int age_vic = Integer.parseInt(agevic.getText());
        double weight_vic = Double.parseDouble(weightvic.getText());
        int a = jSlider1.getValue();
        int damagesize = a;
        
        String[] logcalls = new String[5];
        String numberss = numbers.getText();
        logcalls = numberss.split(",");


        if(jRadioButton27.isSelected()){
            FMR = "Not Found";
        }
        else{
            FMR = (String)fpmr10.getSelectedItem();
        }

        if(jRadioButton30.isSelected()){
            weaponType = (String)headweap.getSelectedItem();
            crimeweaponWeight = Double.parseDouble(crimeweapweight.getText());
        }
        else{
            weaponType = "Not Found";
            crimeweaponWeight = 0.0;
        } 
        
        if(jRadioButton31.isSelected() || jRadioButton29.isSelected() ){
            susweaponWeight = 0.01;
        }
        else{
            susweaponWeight = Double.parseDouble(susweaponweight.getText());
        }

        double sus_force = HeadDamageDeath.totalForceCalc(age_sus, (weight_sus+susweaponWeight));
        double vic_force = HeadDamageDeath.totalForceCalc(age_vic, (weight_vic-damagesize));
      

        if (headdrug.isSelected() == true && headalc.isSelected() == false){
            bloodSample = "Drug found!!";
        }
        else if(headalc.isSelected() == true && headdrug.isSelected() == false){
            bloodSample = "Alcohol has found!!";
        }
        else if(headalc.isSelected() == true && headdrug.isSelected() == true){
            bloodSample = "Drug and Alcohol found!!";
        }
        else{
            bloodSample = "No foreign substance was found in the blood.";
        }

        if (headdrug.isSelected() == true && headalc.isSelected() == false){
            bloodSamplee = "Drug";
        }
        else if(headalc.isSelected() == true && headdrug.isSelected() == false){
            bloodSamplee = "Alcohol";
        }
        else if(headdrug.isSelected() == true && headalc.isSelected() == true){
            bloodSamplee = "";
        }
        else{
            bloodSamplee = " ";
        }

        int rateBs = 0;
        int rateFp = 0;
        int rateHormone = 0;
        int rateCrimeWeapon = 0;
        int ratePhone = 0;
        int totalRate=0;
        int rateForce=0;
        int rateWeaponWeight = 0;


        rateBs = HeadDamageDeath.bloodSample(bloodSamplee);
        rateFp = HeadDamageDeath.FingerprintRate(FMR);
        rateHormone = HeadDamageDeath.hormoneLevel(hormoneLevel);
        ratePhone = HeadDamageDeath.comparePhoneNum(sus_phone, logcalls);
        rateWeaponWeight = HeadDamageDeath.compareweaponWeight(crimeweaponWeight, susweaponWeight);
        rateForce = HeadDamageDeath.compareForce(sus_force, vic_force);

        if (jRadioButton28.isSelected() && jRadioButton30.isSelected()){
            rateCrimeWeapon = HeadDamageDeath.crimeWeapon();
        }
        else{
            rateCrimeWeapon = 0;
        }

        totalRate = rateBs+rateFp+rateHormone+rateCrimeWeapon+ratePhone+rateForce+rateWeaponWeight;

        HeadDamageDeath h = new HeadDamageDeath(suspect_id,sus_name,sus_surname,gender_sus,FMR,age_sus,
            weight_sus, weaponType,susweaponWeight,sus_force,hormoneLevel, bloodSample,sus_phone,totalRate);

        InfoClass.addSuspect(h);
        jTextField4.setText("Suspect added!!");
    }//GEN-LAST:event_addSusButtonActionPerformed

    private void addVictimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVictimButtonActionPerformed
        String vic_name = (String)namevicfield6.getText();
        String vic_surname = (String)surnamevicfield9.getText();
        String gender_vic = (String)gendervic9.getSelectedItem();
        int age_vic = Integer.parseInt(agevic.getText());
        int damagesizee = jSlider1.getValue();
        double weight_vic = Double.parseDouble(weightvic.getText());
        double vic_force = HeadDamageDeath.totalForceCalc(age_vic, (weight_vic-damagesizee));
        double crimeweaponWeight;
        String weaponType;

        String[] logcalls = new String[5];
        String numberss = numbers.getText();
        logcalls = numberss.split(",");

        if(jRadioButton28.isSelected()){
            weaponType = (String)headweap.getSelectedItem();
            crimeweaponWeight = Double.parseDouble(crimeweapweight.getText());
        }
        else{
            weaponType = "Not Found";
            crimeweaponWeight = 0.0;
        }
        

        HeadDamageDeath h = new HeadDamageDeath(vic_name,vic_surname,gender_vic,logcalls,age_vic,weaponType,
            damagesizee,crimeweaponWeight,weight_vic, vic_force);
        InfoClass.addVictim(h);
        jTextField4.setText("Victim added!");

    }//GEN-LAST:event_addVictimButtonActionPerformed

    private void displaybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displaybuttonActionPerformed
        DisplayInfos ds = new DisplayInfos();
        ds.setVisible(true);

        if(InfoClass.suspectList.isEmpty()){
            ds.jTextArea1.append("\nThere are no suspect in the system");
        }
        else{
            ds.jTextArea1.append(InfoClass.getAllSuspect());
            ds.jTextArea3.setText(InfoClass.getAllVictim());
        }
    }//GEN-LAST:event_displaybuttonActionPerformed

    private void guiltybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiltybuttonActionPerformed
        FindGuilty fg = new FindGuilty();
        fg.setVisible(true);

        Crime guilty = InfoClass.findGuilty();

        fg.jTextArea1.append("The max rate is: " + InfoClass.findGuilty().getTotalGuiltyRate()+ ".\nThe max rate is belongs to: "+ guilty.getSuspectId()+
            "\n\nHERE IS THE GUILTY'S INFOS: \n"+ guilty.toString());

    }//GEN-LAST:event_guiltybuttonActionPerformed

    private void deletesuspectbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletesuspectbuttonActionPerformed
        DisplayInfos ds = new DisplayInfos();
        ds.setVisible(true);
        InfoClass.deleteSuspect((String)susIdcomboBox.getSelectedItem());
        susIdcomboBox.removeItem(susIdcomboBox.getSelectedItem());

        ds.jTextArea3.append(InfoClass.getAllVictim());
        ds.jTextArea1.append("The id you selected has been deleted\n\n"+
            "Here is the remaining suspects\n" +InfoClass.getAllSuspect());
    }//GEN-LAST:event_deletesuspectbuttonActionPerformed

    private void deletevictimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletevictimActionPerformed
        DisplayInfos ds = new DisplayInfos();
        ds.setVisible(true);

        InfoClass.deleteVictim(vicdelname.getText());

        ds.jTextArea3.setText("You deleted the victim.\nThere are no victims in the system."+InfoClass.getAllVictim());
        ds.jTextArea1.append(InfoClass.getAllSuspect());
    }//GEN-LAST:event_deletevictimActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
        SearchSuspect ss = new SearchSuspect();
        ss.setVisible(true);

        if(InfoClass.suspectList.isEmpty()){
            ss.jTextArea1.append("\nThere are no suspect in the system");
        }
        else{
            String suspectId = (String)susIdcomboBox.getSelectedItem();
            Crime cd = InfoClass.searchSuspect(suspectId);
            if(cd == null)
            ss.jTextArea1.append("\nSuspect with the id " + suspectId + " is not found");
            else
            ss.jTextArea1.append(cd.toString());
        }
    }//GEN-LAST:event_searchbuttonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       int result = JOptionPane.showConfirmDialog(null,
            "Are you sure you want to exit the program ?\nIf you exit the program, your progress will be lost.", "Exit Confirmation: ",
            JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION)
          setDefaultCloseOperation(DrowningFrame.EXIT_ON_CLOSE);
        else if (result == JOptionPane.NO_OPTION)
          setDefaultCloseOperation(DrowningFrame.DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void headweapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headweapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_headweapActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSusButton;
    private javax.swing.JButton addVictimButton;
    private javax.swing.JTextField agesus3;
    private javax.swing.JTextField agevic;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton clearbutton;
    private javax.swing.JButton closebutton;
    private javax.swing.JTextField crimeweapweight;
    private javax.swing.JPanel cuttingtoolpanel5;
    private javax.swing.JButton deletesuspectbutton;
    private javax.swing.JButton deletevictim;
    private javax.swing.JButton displaybutton;
    private javax.swing.JComboBox<String> fpmr10;
    private javax.swing.JPanel fppanel9;
    private javax.swing.JComboBox<String> gendersus8;
    private javax.swing.JComboBox<String> gendervic9;
    private javax.swing.JButton guiltybutton;
    private javax.swing.JCheckBox headalc;
    private javax.swing.JComboBox<String> headcort4;
    private javax.swing.JCheckBox headdrug;
    private javax.swing.JTextField headsusnum;
    private javax.swing.JComboBox<String> headweap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField namesushead;
    private javax.swing.JTextField namevicfield6;
    private javax.swing.JTextField numbers;
    private javax.swing.JButton searchbutton;
    private javax.swing.JTextField surnamevicfield9;
    private javax.swing.JTextField susId5;
    private javax.swing.JComboBox<String> susIdcomboBox;
    private javax.swing.JTextField sussurnamehead;
    private javax.swing.JTextField susweaponweight;
    private javax.swing.JTextField vicdelname;
    private javax.swing.JTextField weightvic;
    private javax.swing.JTextField wsus3;
    // End of variables declaration//GEN-END:variables
}
