/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import javax.swing.JOptionPane;

/**
 *
 * @author ebrue
 */
public class KidnappingFrame extends javax.swing.JFrame {

    AdultKidnappingFrame akf;
    ChildKidnappingFrame ckf;
    public KidnappingFrame() {
        initComponents();
        this.setSize(440,275);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel70 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        adultkidbutton = new javax.swing.JRadioButton();
        childkidbutton = new javax.swing.JRadioButton();
        closebutton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kidnapping");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel70.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(204, 0, 0));
        jLabel70.setText("Criminal Detection System");
        getContentPane().add(jLabel70);
        jLabel70.setBounds(20, 20, 390, 20);

        jLabel6.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Type of kidnapping");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 50, 170, 24);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("(Make Your Selection and Press Enter)");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 80, 300, 20);

        buttonGroup1.add(adultkidbutton);
        adultkidbutton.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        adultkidbutton.setForeground(new java.awt.Color(255, 255, 255));
        adultkidbutton.setText("ADULT KIDNAPPING");
        adultkidbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adultkidbutton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adultkidbuttonKeyPressed(evt);
            }
        });
        getContentPane().add(adultkidbutton);
        adultkidbutton.setBounds(20, 120, 220, 28);

        buttonGroup1.add(childkidbutton);
        childkidbutton.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        childkidbutton.setForeground(new java.awt.Color(255, 255, 255));
        childkidbutton.setText("CHILD KIDNAPPING");
        childkidbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        childkidbutton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                childkidbuttonKeyPressed(evt);
            }
        });
        getContentPane().add(childkidbutton);
        childkidbutton.setBounds(20, 160, 200, 28);

        closebutton.setBackground(new java.awt.Color(0, 0, 0));
        closebutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        closebutton.setForeground(new java.awt.Color(255, 255, 255));
        closebutton.setText("CLOSE FRAME");
        closebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(closebutton);
        closebutton.setBounds(260, 190, 150, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifes/car.gif"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-70, -10, 560, 250);

        setSize(new java.awt.Dimension(440, 242));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adultkidbuttonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adultkidbuttonKeyPressed
        akf = new AdultKidnappingFrame();
        akf.setVisible(true);
    }//GEN-LAST:event_adultkidbuttonKeyPressed

    private void childkidbuttonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_childkidbuttonKeyPressed
        ckf = new ChildKidnappingFrame();
        ckf.setVisible(true);
    }//GEN-LAST:event_childkidbuttonKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      int result = JOptionPane.showConfirmDialog(null,
            "Are you sure you want to exit the program ?\nIf you exit the program, your progress will be lost.", "Exit Confirmation: ",
            JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION)
          setDefaultCloseOperation(DrowningFrame.EXIT_ON_CLOSE);
        else if (result == JOptionPane.NO_OPTION)
          setDefaultCloseOperation(DrowningFrame.DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void closebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebuttonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closebuttonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adultkidbutton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton childkidbutton;
    private javax.swing.JButton closebutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel70;
    // End of variables declaration//GEN-END:variables
}
