/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import javax.swing.JOptionPane;
import Crime.*;

public class NarcoticCrimesFrame extends javax.swing.JFrame {

    /**
     * Creates new form ItCrimesFrame
     */
    public NarcoticCrimesFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        narcoticcrimespanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameaddict = new javax.swing.JTextField();
        surnamesus = new javax.swing.JTextField();
        gendersus = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        numbers = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        location = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        substance = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        conperson = new javax.swing.JTextField();
        ageaddict = new javax.swing.JTextField();
        addaddict = new javax.swing.JButton();
        namesus = new javax.swing.JTextField();
        surnameaddict = new javax.swing.JTextField();
        genderaddict = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        searchbutton = new javax.swing.JButton();
        susIdcomboBox = new javax.swing.JComboBox<>();
        deletesuspect = new javax.swing.JButton();
        vicdelname = new javax.swing.JTextField();
        displaybutton = new javax.swing.JButton();
        clearbutton = new javax.swing.JButton();
        guiltybutton = new javax.swing.JButton();
        closebutton = new javax.swing.JButton();
        susphonenum = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        location1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        deletevictim = new javax.swing.JButton();
        addsuspect = new javax.swing.JButton();
        susId1 = new javax.swing.JTextField();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Narcotic Crimes");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        narcoticcrimespanel.setBackground(new java.awt.Color(0, 51, 51));
        narcoticcrimespanel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Substance Addict's Infos");
        narcoticcrimespanel.add(jLabel1);
        jLabel1.setBounds(10, 40, 210, 21);

        nameaddict.setBackground(new java.awt.Color(255, 255, 255));
        nameaddict.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        nameaddict.setForeground(new java.awt.Color(0, 0, 0));
        narcoticcrimespanel.add(nameaddict);
        nameaddict.setBounds(150, 80, 110, 26);

        surnamesus.setBackground(new java.awt.Color(255, 255, 255));
        surnamesus.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        surnamesus.setForeground(new java.awt.Color(0, 0, 0));
        narcoticcrimespanel.add(surnamesus);
        surnamesus.setBounds(600, 160, 110, 26);

        gendersus.setBackground(new java.awt.Color(255, 255, 255));
        gendersus.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        gendersus.setForeground(new java.awt.Color(0, 0, 0));
        gendersus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        gendersus.setSelectedIndex(-1);
        narcoticcrimespanel.add(gendersus);
        gendersus.setBounds(600, 200, 110, 26);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        numbers.setBackground(new java.awt.Color(255, 255, 255));
        numbers.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        numbers.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last 5 Call Logs:");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("(separate with commas)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(30, 30, 30)
                        .addComponent(numbers, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel13)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numbers, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );

        narcoticcrimespanel.add(jPanel4);
        jPanel4.setBounds(10, 250, 300, 60);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Where s/he was last seen?");

        location.setBackground(new java.awt.Color(255, 255, 255));
        location.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        location.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(location, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        narcoticcrimespanel.add(jPanel2);
        jPanel2.setBounds(10, 400, 300, 38);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Substance to Which the Person is Addicted");

        substance.setBackground(new java.awt.Color(255, 255, 255));
        substance.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        substance.setForeground(new java.awt.Color(0, 0, 0));
        substance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cocaine", "Marijuana", "Bonsai", "Ecstasy Pill", "Amphetamine", "Methamphetamine", "Cannabis", " ", " " }));
        substance.setSelectedIndex(-1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(substance, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(substance, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        narcoticcrimespanel.add(jPanel3);
        jPanel3.setBounds(10, 450, 300, 74);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Last 5 People Contacted:");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("(Enter person's name and separate with commas)");

        conperson.setBackground(new java.awt.Color(255, 255, 255));
        conperson.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        conperson.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(conperson)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel15)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(conperson, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        narcoticcrimespanel.add(jPanel5);
        jPanel5.setBounds(10, 330, 300, 59);

        ageaddict.setBackground(new java.awt.Color(255, 255, 255));
        ageaddict.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ageaddict.setForeground(new java.awt.Color(0, 0, 0));
        narcoticcrimespanel.add(ageaddict);
        ageaddict.setBounds(150, 200, 110, 26);

        addaddict.setBackground(new java.awt.Color(0, 0, 0));
        addaddict.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        addaddict.setForeground(new java.awt.Color(255, 255, 255));
        addaddict.setText("ADD ADDICT");
        addaddict.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addaddict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addaddictActionPerformed(evt);
            }
        });
        narcoticcrimespanel.add(addaddict);
        addaddict.setBounds(64, 577, 137, 31);

        namesus.setBackground(new java.awt.Color(255, 255, 255));
        namesus.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        namesus.setForeground(new java.awt.Color(0, 0, 0));
        narcoticcrimespanel.add(namesus);
        namesus.setBounds(600, 120, 110, 26);

        surnameaddict.setBackground(new java.awt.Color(255, 255, 255));
        surnameaddict.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        surnameaddict.setForeground(new java.awt.Color(0, 0, 0));
        narcoticcrimespanel.add(surnameaddict);
        surnameaddict.setBounds(150, 120, 110, 26);

        genderaddict.setBackground(new java.awt.Color(255, 255, 255));
        genderaddict.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        genderaddict.setForeground(new java.awt.Color(0, 0, 0));
        genderaddict.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        genderaddict.setSelectedIndex(-1);
        narcoticcrimespanel.add(genderaddict);
        genderaddict.setBounds(150, 160, 110, 26);

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        narcoticcrimespanel.add(jTextField1);
        jTextField1.setBounds(820, 80, 200, 26);

        searchbutton.setBackground(new java.awt.Color(0, 0, 0));
        searchbutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        searchbutton.setForeground(new java.awt.Color(255, 255, 255));
        searchbutton.setText("SEARCH FOR SUSPECT");
        searchbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });
        narcoticcrimespanel.add(searchbutton);
        searchbutton.setBounds(820, 160, 200, 40);

        susIdcomboBox.setBackground(new java.awt.Color(255, 255, 255));
        susIdcomboBox.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        susIdcomboBox.setForeground(new java.awt.Color(0, 0, 0));
        narcoticcrimespanel.add(susIdcomboBox);
        susIdcomboBox.setBounds(940, 120, 81, 26);

        deletesuspect.setBackground(new java.awt.Color(0, 0, 0));
        deletesuspect.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        deletesuspect.setForeground(new java.awt.Color(255, 255, 255));
        deletesuspect.setText("DELETE SUSPECT");
        deletesuspect.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletesuspect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletesuspectActionPerformed(evt);
            }
        });
        narcoticcrimespanel.add(deletesuspect);
        deletesuspect.setBounds(820, 210, 200, 40);

        vicdelname.setBackground(new java.awt.Color(255, 255, 255));
        vicdelname.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        vicdelname.setForeground(new java.awt.Color(0, 0, 0));
        narcoticcrimespanel.add(vicdelname);
        vicdelname.setBounds(940, 310, 80, 26);

        displaybutton.setBackground(new java.awt.Color(0, 0, 0));
        displaybutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        displaybutton.setForeground(new java.awt.Color(255, 255, 255));
        displaybutton.setText("DISPLAY CRIME INFOS");
        displaybutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        displaybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displaybuttonActionPerformed(evt);
            }
        });
        narcoticcrimespanel.add(displaybutton);
        displaybutton.setBounds(820, 450, 200, 40);

        clearbutton.setBackground(new java.awt.Color(0, 0, 0));
        clearbutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        clearbutton.setForeground(new java.awt.Color(255, 255, 255));
        clearbutton.setText("CLEAR FIELDS");
        clearbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });
        narcoticcrimespanel.add(clearbutton);
        clearbutton.setBounds(820, 500, 200, 42);

        guiltybutton.setBackground(new java.awt.Color(0, 0, 0));
        guiltybutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        guiltybutton.setForeground(new java.awt.Color(255, 255, 255));
        guiltybutton.setText("FIND DRUG DEALER");
        guiltybutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guiltybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiltybuttonActionPerformed(evt);
            }
        });
        narcoticcrimespanel.add(guiltybutton);
        guiltybutton.setBounds(820, 550, 200, 40);

        closebutton.setBackground(new java.awt.Color(0, 0, 0));
        closebutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        closebutton.setForeground(new java.awt.Color(255, 255, 255));
        closebutton.setText("Close Frame");
        closebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebuttonMouseClicked(evt);
            }
        });
        narcoticcrimespanel.add(closebutton);
        closebutton.setBounds(860, 600, 130, 30);

        susphonenum.setBackground(new java.awt.Color(255, 255, 255));
        susphonenum.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        susphonenum.setForeground(new java.awt.Color(0, 0, 0));
        narcoticcrimespanel.add(susphonenum);
        susphonenum.setBounds(600, 240, 110, 26);

        jLabel19.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Where s/he was last seen?");
        narcoticcrimespanel.add(jLabel19);
        jLabel19.setBounds(410, 280, 180, 20);

        location1.setBackground(new java.awt.Color(255, 255, 255));
        location1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        location1.setForeground(new java.awt.Color(0, 0, 0));
        narcoticcrimespanel.add(location1);
        location1.setBounds(600, 280, 110, 26);

        jLabel20.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Was the specified foreign ");
        narcoticcrimespanel.add(jLabel20);
        jLabel20.setBounds(410, 340, 180, 18);

        jLabel21.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("substance found on any property");
        narcoticcrimespanel.add(jLabel21);
        jLabel21.setBounds(410, 360, 220, 18);

        jLabel22.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("belonging to the suspect?");
        narcoticcrimespanel.add(jLabel22);
        jLabel22.setBounds(410, 380, 180, 18);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Yes");
        narcoticcrimespanel.add(jRadioButton1);
        jRadioButton1.setBounds(660, 340, 58, 20);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("No");
        narcoticcrimespanel.add(jRadioButton2);
        jRadioButton2.setBounds(660, 370, 58, 22);

        jLabel23.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Is there any foreign substance ");
        narcoticcrimespanel.add(jLabel23);
        jLabel23.setBounds(410, 440, 210, 20);

        jLabel24.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("in the suspect's blood?");
        narcoticcrimespanel.add(jLabel24);
        jLabel24.setBounds(410, 460, 170, 18);

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Yes");
        narcoticcrimespanel.add(jRadioButton3);
        jRadioButton3.setBounds(660, 430, 56, 20);

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("No");
        narcoticcrimespanel.add(jRadioButton4);
        jRadioButton4.setBounds(660, 460, 53, 22);

        deletevictim.setBackground(new java.awt.Color(0, 0, 0));
        deletevictim.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        deletevictim.setForeground(new java.awt.Color(255, 255, 255));
        deletevictim.setText("DELETE ADDICT");
        deletevictim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletevictim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletevictimActionPerformed(evt);
            }
        });
        narcoticcrimespanel.add(deletevictim);
        deletevictim.setBounds(820, 350, 200, 40);

        addsuspect.setBackground(new java.awt.Color(0, 0, 0));
        addsuspect.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        addsuspect.setForeground(new java.awt.Color(255, 255, 255));
        addsuspect.setText("ADD SUSPECT");
        addsuspect.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addsuspect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsuspectActionPerformed(evt);
            }
        });
        narcoticcrimespanel.add(addsuspect);
        addsuspect.setBounds(480, 570, 140, 31);

        susId1.setBackground(new java.awt.Color(255, 255, 255));
        susId1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        susId1.setForeground(new java.awt.Color(0, 0, 0));
        narcoticcrimespanel.add(susId1);
        susId1.setBounds(600, 80, 110, 26);

        jLabel79.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(153, 0, 0));
        jLabel79.setText("NARCOTIC CRIMES");
        narcoticcrimespanel.add(jLabel79);
        jLabel79.setBounds(10, 10, 180, 24);

        jLabel80.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(255, 255, 255));
        jLabel80.setText("Name:");
        narcoticcrimespanel.add(jLabel80);
        jLabel80.setBounds(10, 80, 88, 18);

        jLabel26.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Surname:");
        narcoticcrimespanel.add(jLabel26);
        jLabel26.setBounds(10, 120, 70, 18);

        jLabel81.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(255, 255, 255));
        jLabel81.setText("Gender:");
        narcoticcrimespanel.add(jLabel81);
        jLabel81.setBounds(10, 160, 84, 18);

        jLabel82.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(255, 255, 255));
        jLabel82.setText("Age:");
        narcoticcrimespanel.add(jLabel82);
        jLabel82.setBounds(10, 200, 84, 18);

        jLabel27.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Suspect's Infos");
        narcoticcrimespanel.add(jLabel27);
        jLabel27.setBounds(410, 40, 170, 21);

        jLabel28.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Suspect ID:");
        narcoticcrimespanel.add(jLabel28);
        jLabel28.setBounds(410, 80, 81, 18);

        jLabel29.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Name:");
        narcoticcrimespanel.add(jLabel29);
        jLabel29.setBounds(410, 120, 90, 18);

        jLabel30.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Surname:");
        narcoticcrimespanel.add(jLabel30);
        jLabel30.setBounds(410, 160, 90, 18);

        jLabel31.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Gender:");
        narcoticcrimespanel.add(jLabel31);
        jLabel31.setBounds(410, 200, 70, 18);

        jLabel32.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Phone Number:");
        narcoticcrimespanel.add(jLabel32);
        jLabel32.setBounds(410, 240, 110, 18);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Suspect ID:");
        narcoticcrimespanel.add(jLabel4);
        jLabel4.setBounds(820, 120, 79, 25);

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Addict's Name:");
        narcoticcrimespanel.add(jLabel10);
        jLabel10.setBounds(820, 320, 100, 18);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifes/wallpaper1.png"))); // NOI18N
        narcoticcrimespanel.add(jLabel3);
        jLabel3.setBounds(-90, 0, 1160, 730);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(narcoticcrimespanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1042, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(narcoticcrimespanel, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int result = JOptionPane.showConfirmDialog(null,
            "Are you sure you want to exit the program ?\nIf you exit the program, your progress will be lost.", "Exit Confirmation: ",
            JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION)
          setDefaultCloseOperation(DrowningFrame.EXIT_ON_CLOSE);
        else if (result == JOptionPane.NO_OPTION)
          setDefaultCloseOperation(DrowningFrame.DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void deletevictimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletevictimActionPerformed
        DisplayInfos ds = new DisplayInfos();
        ds.setVisible(true);

        InfoClass.deleteVictim(vicdelname.getText());

        ds.jTextArea3.setText("You deleted the victim.\nThere are no victims in the system."+InfoClass.getAllVictim());
        ds.jTextArea1.append(InfoClass.getAllSuspect());
    }//GEN-LAST:event_deletevictimActionPerformed

    private void closebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebuttonMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_closebuttonMouseClicked

    private void guiltybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiltybuttonActionPerformed
        FindGuilty fg = new FindGuilty();
        fg.setVisible(true);
        Crime guilty = InfoClass.findGuilty();

        fg.jTextArea1.append("The max rate is: " + InfoClass.findGuilty().getTotalGuiltyRate()+ ".\nThe max rate is belongs to: "+ guilty.getSuspectId()+
            "\n\nHERE IS THE DRUG DEALER'S INFOS: \n"+ guilty.toString());
    }//GEN-LAST:event_guiltybuttonActionPerformed

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        susId1.setText("");
        namesus.setText("");
        surnamesus.setText("");
        gendersus.setSelectedItem(null);
        susphonenum.setText("");
        location1.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
    }//GEN-LAST:event_clearbuttonActionPerformed

    private void displaybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displaybuttonActionPerformed
        DisplayInfos ds = new DisplayInfos();
        ds.setVisible(true);
        if(InfoClass.suspectList.isEmpty()){
            ds.jTextArea1.append("\nThere are no suspect in the system");
        }
        else{
            ds.jTextArea1.append(InfoClass.getAllSuspect());
            ds.jTextArea3.setText(InfoClass.getAllVictim());
        }
    }//GEN-LAST:event_displaybuttonActionPerformed

    private void deletesuspectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletesuspectActionPerformed
        DisplayInfos ds = new DisplayInfos();
        ds.setVisible(true);
        InfoClass.deleteSuspect((String)susIdcomboBox.getSelectedItem());
        susIdcomboBox.removeItem(susIdcomboBox.getSelectedItem());

        ds.jTextArea3.append(InfoClass.getAllVictim());
        ds.jTextArea1.append("The id you selected has been deleted\n\n"+
            "Here is the remaining suspects\n" +InfoClass.getAllSuspect());
    }//GEN-LAST:event_deletesuspectActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
        SearchSuspect ss = new SearchSuspect();
        ss.setVisible(true);

        if(InfoClass.suspectList.isEmpty()){
            ss.jTextArea1.append("\nThere are no suspect in the system");
        }
        else{
            String suspectId = (String)susIdcomboBox.getSelectedItem();
            Crime cd = InfoClass.searchSuspect(suspectId);
            if(cd == null)
            ss.jTextArea1.append("\nSuspect with the id " + suspectId + " is not found");
            else
            ss.jTextArea1.append(cd.toString());
        }
    }//GEN-LAST:event_searchbuttonActionPerformed

    private void addaddictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addaddictActionPerformed
     String addict_name = nameaddict.getText();
     String addict_surname = surnameaddict.getText();
     String gender = (String)genderaddict.getSelectedItem();
     int age = Integer.parseInt(ageaddict.getText());
    
     String[] logcalls = new String[5];
     String numberss = numbers.getText();
     logcalls = numberss.split(",");
     
     String[] persons = new String[5];
     String humans = conperson.getText();
     persons = humans.split(",");
     
     String addictLoc = location.getText();
     String addictSubstance = (String)substance.getSelectedItem();
     
     NarcoticCrimes n = new NarcoticCrimes(addict_name,addict_surname,gender,age,logcalls,persons,addictLoc,addictSubstance);
     InfoClass.addVictim(n);
     jTextField1.setText("Adddict added!");
    }//GEN-LAST:event_addaddictActionPerformed

    private void addsuspectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsuspectActionPerformed
     String suspect_id = susId1.getText();
     String sus_name = namesus.getText();
     String sus_surname = surnamesus.getText();
     String gender_sus = (String)gendersus.getSelectedItem();
     String susNum = susphonenum.getText();
     String sus_loc = location1.getText();
     String addictLoc = location.getText();
     int addict_age = Integer.parseInt(ageaddict.getText());
     susIdcomboBox.addItem(suspect_id);

     
     String[] logcalls = new String[5];
     String numberss = numbers.getText();
     logcalls = numberss.split(",");
     
     String[] persons = new String[5];
     String humans = conperson.getText();
     persons = humans.split(",");
     
     int totalRate, cpnRate, cnRate, cllRate, fsRate, fibRate, ageRate = 0;
     
     String foundSubstance;
     String foundInBlood;
     if(jRadioButton1.isSelected()){
         foundSubstance = jRadioButton1.getText();
         fsRate = NarcoticCrimes.foundSubstanceRate();
     }
     else{
         foundSubstance = jRadioButton2.getText();
         fsRate = 0;
     }
     
     if(jRadioButton3.isSelected()){
         foundInBlood = jRadioButton3.getText();
         fibRate = NarcoticCrimes.foundInBloodRate();
     }
     else{
         foundInBlood = jRadioButton4.getText();
         fibRate = 0;
     }
     
     
     
     cpnRate = NarcoticCrimes.comparePhoneNum(susNum, logcalls);
     cnRate = NarcoticCrimes.compareName(sus_name, persons);
     cllRate = NarcoticCrimes.compareLastLocation(addictLoc, sus_loc);
     ageRate = NarcoticCrimes.ageRate(addict_age);
     
     totalRate = cpnRate + cnRate + cllRate + fsRate + fibRate + ageRate;
     
     NarcoticCrimes n = new NarcoticCrimes(suspect_id,sus_name,sus_surname,gender_sus,totalRate,susNum,sus_loc,foundSubstance,foundInBlood);
     InfoClass.addSuspect(n);
     jTextField1.setText("Suspect added!");
     
     
     
    }//GEN-LAST:event_addsuspectActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addaddict;
    private javax.swing.JButton addsuspect;
    private javax.swing.JTextField ageaddict;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton clearbutton;
    private javax.swing.JButton closebutton;
    private javax.swing.JTextField conperson;
    private javax.swing.JButton deletesuspect;
    private javax.swing.JButton deletevictim;
    private javax.swing.JButton displaybutton;
    private javax.swing.JComboBox<String> genderaddict;
    private javax.swing.JComboBox<String> gendersus;
    private javax.swing.JButton guiltybutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField location;
    private javax.swing.JTextField location1;
    private javax.swing.JTextField nameaddict;
    private javax.swing.JTextField namesus;
    private javax.swing.JPanel narcoticcrimespanel;
    private javax.swing.JTextField numbers;
    private javax.swing.JButton searchbutton;
    private javax.swing.JComboBox<String> substance;
    private javax.swing.JTextField surnameaddict;
    private javax.swing.JTextField surnamesus;
    private javax.swing.JTextField susId1;
    private javax.swing.JComboBox<String> susIdcomboBox;
    private javax.swing.JTextField susphonenum;
    private javax.swing.JTextField vicdelname;
    // End of variables declaration//GEN-END:variables
}
