/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import Crime.*;
import javax.swing.JOptionPane;
/**
 *
 * @author ebrue
 */
public class WithAGunFrame extends javax.swing.JFrame {

    /**
     * Creates new form WithAGun
     */
    public WithAGunFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        withagunpanel2 = new javax.swing.JPanel();
        namevicfield4 = new javax.swing.JTextField();
        gendervic4 = new javax.swing.JComboBox<>();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jLabel37 = new javax.swing.JLabel();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        serialNum1 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        gunserialnumber = new javax.swing.JTextField();
        jRadioButton13 = new javax.swing.JRadioButton();
        susId2 = new javax.swing.JTextField();
        namesusfield2 = new javax.swing.JTextField();
        gendersus2 = new javax.swing.JComboBox<>();
        fppanel3 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        fpmr4 = new javax.swing.JComboBox<>();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        serialNum2 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        susserialnumber = new javax.swing.JTextField();
        jRadioButton16 = new javax.swing.JRadioButton();
        jPanel14 = new javax.swing.JPanel();
        drowsus2 = new javax.swing.JCheckBox();
        drowalc2 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        numbers = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        gunsusnum = new javax.swing.JTextField();
        surnamevic = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        crimediameter = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        addbutton = new javax.swing.JButton();
        addvicbutton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        susbulldia = new javax.swing.JTextField();
        sussurname = new javax.swing.JTextField();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jLabel47 = new javax.swing.JLabel();
        drowcort2 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        searchbutton = new javax.swing.JButton();
        susIdcomboBox = new javax.swing.JComboBox<>();
        deletebutton = new javax.swing.JButton();
        vicdelname = new javax.swing.JTextField();
        deletevictim = new javax.swing.JButton();
        displaybutton = new javax.swing.JButton();
        clearbutton = new javax.swing.JButton();
        guiltybutton = new javax.swing.JButton();
        closebutton = new javax.swing.JButton();
        jLabel79 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gun Death");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        withagunpanel2.setLayout(null);

        namevicfield4.setBackground(new java.awt.Color(255, 255, 255));
        namevicfield4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        namevicfield4.setForeground(new java.awt.Color(0, 0, 0));
        withagunpanel2.add(namevicfield4);
        namevicfield4.setBounds(130, 70, 110, 26);

        gendervic4.setBackground(new java.awt.Color(255, 255, 255));
        gendervic4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        gendervic4.setForeground(new java.awt.Color(0, 0, 0));
        gendervic4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        gendervic4.setSelectedIndex(-1);
        withagunpanel2.add(gendervic4);
        gendervic4.setBounds(130, 150, 110, 26);

        buttonGroup2.add(jRadioButton9);
        jRadioButton9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton9.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton9.setText("Yes");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });
        withagunpanel2.add(jRadioButton9);
        jRadioButton9.setBounds(20, 390, 56, 22);

        buttonGroup2.add(jRadioButton10);
        jRadioButton10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton10.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton10.setText("No");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });
        withagunpanel2.add(jRadioButton10);
        jRadioButton10.setBounds(90, 390, 50, 22);

        jLabel37.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Have bullets been found in the body?");
        withagunpanel2.add(jLabel37);
        jLabel37.setBounds(10, 520, 250, 18);

        buttonGroup3.add(jRadioButton11);
        jRadioButton11.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton11.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton11.setText("Yes");
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });
        withagunpanel2.add(jRadioButton11);
        jRadioButton11.setBounds(20, 550, 60, 22);

        buttonGroup3.add(jRadioButton12);
        jRadioButton12.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton12.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton12.setText("No");
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });
        withagunpanel2.add(jRadioButton12);
        jRadioButton12.setBounds(90, 550, 60, 22);

        serialNum1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel38.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Enter gun's serial number: ");

        gunserialnumber.setBackground(new java.awt.Color(255, 255, 255));
        gunserialnumber.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        gunserialnumber.setForeground(new java.awt.Color(0, 0, 0));

        jRadioButton13.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton13.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton13.setText("None");

        javax.swing.GroupLayout serialNum1Layout = new javax.swing.GroupLayout(serialNum1);
        serialNum1.setLayout(serialNum1Layout);
        serialNum1Layout.setHorizontalGroup(
            serialNum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serialNum1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(serialNum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gunserialnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        serialNum1Layout.setVerticalGroup(
            serialNum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serialNum1Layout.createSequentialGroup()
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gunserialnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton13))
        );

        withagunpanel2.add(serialNum1);
        serialNum1.setBounds(10, 440, 240, 80);

        susId2.setBackground(new java.awt.Color(255, 255, 255));
        susId2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        susId2.setForeground(new java.awt.Color(0, 0, 0));
        withagunpanel2.add(susId2);
        susId2.setBounds(400, 70, 100, 26);

        namesusfield2.setBackground(new java.awt.Color(255, 255, 255));
        namesusfield2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        namesusfield2.setForeground(new java.awt.Color(0, 0, 0));
        withagunpanel2.add(namesusfield2);
        namesusfield2.setBounds(400, 110, 100, 26);

        gendersus2.setBackground(new java.awt.Color(255, 255, 255));
        gendersus2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        gendersus2.setForeground(new java.awt.Color(0, 0, 0));
        gendersus2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        gendersus2.setSelectedIndex(-1);
        withagunpanel2.add(gendersus2);
        gendersus2.setBounds(400, 190, 100, 26);

        fppanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel59.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Fingerprint Match Rate:");

        fpmr4.setBackground(new java.awt.Color(255, 255, 255));
        fpmr4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        fpmr4.setForeground(new java.awt.Color(0, 0, 0));
        fpmr4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "25", "50", "75", "100" }));
        fpmr4.setSelectedIndex(-1);
        fpmr4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fpmr4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fppanel3Layout = new javax.swing.GroupLayout(fppanel3);
        fppanel3.setLayout(fppanel3Layout);
        fppanel3Layout.setHorizontalGroup(
            fppanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fppanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fpmr4, 0, 66, Short.MAX_VALUE)
                .addContainerGap())
        );
        fppanel3Layout.setVerticalGroup(
            fppanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fppanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(fppanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59)
                    .addComponent(fpmr4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        withagunpanel2.add(fppanel3);
        fppanel3.setBounds(296, 280, 250, 40);

        buttonGroup4.add(jRadioButton14);
        jRadioButton14.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton14.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton14.setText("Yes");
        jRadioButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton14ActionPerformed(evt);
            }
        });
        withagunpanel2.add(jRadioButton14);
        jRadioButton14.setBounds(310, 250, 81, 22);

        buttonGroup4.add(jRadioButton15);
        jRadioButton15.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton15.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton15.setText("No");
        jRadioButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton15ActionPerformed(evt);
            }
        });
        withagunpanel2.add(jRadioButton15);
        jRadioButton15.setBounds(390, 250, 69, 22);

        serialNum2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel46.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Enter gun's serial number: ");

        susserialnumber.setBackground(new java.awt.Color(255, 255, 255));
        susserialnumber.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        susserialnumber.setForeground(new java.awt.Color(0, 0, 0));

        jRadioButton16.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton16.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton16.setText("None");

        javax.swing.GroupLayout serialNum2Layout = new javax.swing.GroupLayout(serialNum2);
        serialNum2.setLayout(serialNum2Layout);
        serialNum2Layout.setHorizontalGroup(
            serialNum2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serialNum2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(serialNum2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(susserialnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        serialNum2Layout.setVerticalGroup(
            serialNum2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serialNum2Layout.createSequentialGroup()
                .addComponent(jLabel46)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(susserialnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        withagunpanel2.add(serialNum2);
        serialNum2.setBounds(300, 330, 240, 80);

        jPanel14.setBackground(new java.awt.Color(0, 0, 0));
        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Found in Blood", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        drowsus2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        drowsus2.setForeground(new java.awt.Color(255, 255, 255));
        drowsus2.setText("Drug");

        drowalc2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        drowalc2.setForeground(new java.awt.Color(255, 255, 255));
        drowalc2.setText("Alcohol");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(drowsus2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drowalc2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drowsus2)
                    .addComponent(drowalc2))
                .addContainerGap())
        );

        withagunpanel2.add(jPanel14);
        jPanel14.setBounds(300, 490, 240, 60);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        numbers.setBackground(new java.awt.Color(255, 255, 255));
        numbers.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        numbers.setForeground(new java.awt.Color(0, 0, 0));
        numbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbersActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last 5 Call Logs:");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("(separate with commas)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numbers)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel13)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numbers, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );

        withagunpanel2.add(jPanel4);
        jPanel4.setBounds(10, 200, 240, 60);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone Number:");
        withagunpanel2.add(jLabel4);
        jLabel4.setBounds(310, 570, 106, 18);

        gunsusnum.setBackground(new java.awt.Color(255, 255, 255));
        gunsusnum.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        gunsusnum.setForeground(new java.awt.Color(0, 0, 0));
        withagunpanel2.add(gunsusnum);
        gunsusnum.setBounds(420, 560, 100, 26);

        surnamevic.setBackground(new java.awt.Color(255, 255, 255));
        surnamevic.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        surnamevic.setForeground(new java.awt.Color(0, 0, 0));
        withagunpanel2.add(surnamevic);
        surnamevic.setBounds(130, 110, 110, 26);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Enter the bullet's diameter");

        crimediameter.setBackground(new java.awt.Color(255, 255, 255));
        crimediameter.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        crimediameter.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(crimediameter, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(12, 12, 12)
                .addComponent(crimediameter, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        withagunpanel2.add(jPanel2);
        jPanel2.setBounds(10, 580, 240, 70);

        jLabel45.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Are there any gun found on the suspect?");
        withagunpanel2.add(jLabel45);
        jLabel45.setBounds(310, 220, 270, 18);

        addbutton.setBackground(new java.awt.Color(0, 0, 0));
        addbutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        addbutton.setForeground(new java.awt.Color(255, 255, 255));
        addbutton.setText("ADD SUSPECT");
        addbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });
        withagunpanel2.add(addbutton);
        addbutton.setBounds(340, 660, 130, 30);

        addvicbutton.setBackground(new java.awt.Color(0, 0, 0));
        addvicbutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        addvicbutton.setForeground(new java.awt.Color(255, 255, 255));
        addvicbutton.setText("ADD VICTIM");
        addvicbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addvicbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addvicbuttonActionPerformed(evt);
            }
        });
        withagunpanel2.add(addvicbutton);
        addvicbutton.setBounds(50, 660, 120, 30);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Enter the gun's bullet diameter");

        susbulldia.setBackground(new java.awt.Color(255, 255, 255));
        susbulldia.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        susbulldia.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(susbulldia, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(12, 12, 12)
                .addComponent(susbulldia, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        withagunpanel2.add(jPanel3);
        jPanel3.setBounds(300, 420, 240, 60);

        sussurname.setBackground(new java.awt.Color(255, 255, 255));
        sussurname.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        sussurname.setForeground(new java.awt.Color(0, 0, 0));
        withagunpanel2.add(sussurname);
        sussurname.setBounds(400, 150, 100, 26);

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton7.setText("Yes");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        withagunpanel2.add(jRadioButton7);
        jRadioButton7.setBounds(20, 300, 62, 22);

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButton8.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton8.setText("No");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });
        withagunpanel2.add(jRadioButton8);
        jRadioButton8.setBounds(90, 300, 51, 22);

        jLabel47.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Cortisol and Adrenaline Level:");
        withagunpanel2.add(jLabel47);
        jLabel47.setBounds(310, 590, 220, 26);

        drowcort2.setBackground(new java.awt.Color(255, 255, 255));
        drowcort2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        drowcort2.setForeground(new java.awt.Color(0, 0, 0));
        drowcort2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "At Reference Value", "Above the Reference Value" }));
        drowcort2.setSelectedIndex(-1);
        withagunpanel2.add(drowcort2);
        drowcort2.setBounds(310, 620, 230, 30);

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 0, 0));
        withagunpanel2.add(jTextField3);
        jTextField3.setBounds(640, 60, 200, 26);

        searchbutton.setBackground(new java.awt.Color(0, 0, 0));
        searchbutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        searchbutton.setForeground(new java.awt.Color(255, 255, 255));
        searchbutton.setText("SEARCH FOR SUSPECT");
        searchbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });
        withagunpanel2.add(searchbutton);
        searchbutton.setBounds(640, 140, 200, 42);

        susIdcomboBox.setBackground(new java.awt.Color(255, 255, 255));
        susIdcomboBox.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        susIdcomboBox.setForeground(new java.awt.Color(0, 0, 0));
        withagunpanel2.add(susIdcomboBox);
        susIdcomboBox.setBounds(740, 100, 93, 26);

        deletebutton.setBackground(new java.awt.Color(0, 0, 0));
        deletebutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        deletebutton.setForeground(new java.awt.Color(255, 255, 255));
        deletebutton.setText("DELETE SUSPECT");
        deletebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        withagunpanel2.add(deletebutton);
        deletebutton.setBounds(640, 190, 200, 40);

        vicdelname.setBackground(new java.awt.Color(255, 255, 255));
        vicdelname.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        vicdelname.setForeground(new java.awt.Color(0, 0, 0));
        withagunpanel2.add(vicdelname);
        vicdelname.setBounds(760, 290, 80, 26);

        deletevictim.setBackground(new java.awt.Color(0, 0, 0));
        deletevictim.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        deletevictim.setForeground(new java.awt.Color(255, 255, 255));
        deletevictim.setText("DELETE VICTIM");
        deletevictim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletevictim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletevictimActionPerformed(evt);
            }
        });
        withagunpanel2.add(deletevictim);
        deletevictim.setBounds(640, 330, 200, 40);

        displaybutton.setBackground(new java.awt.Color(0, 0, 0));
        displaybutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        displaybutton.setForeground(new java.awt.Color(255, 255, 255));
        displaybutton.setText("DISPLAY CRIME INFOS");
        displaybutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        displaybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displaybuttonActionPerformed(evt);
            }
        });
        withagunpanel2.add(displaybutton);
        displaybutton.setBounds(640, 460, 200, 40);

        clearbutton.setBackground(new java.awt.Color(0, 0, 0));
        clearbutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        clearbutton.setForeground(new java.awt.Color(255, 255, 255));
        clearbutton.setText("CLEAR FIELDS");
        clearbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });
        withagunpanel2.add(clearbutton);
        clearbutton.setBounds(640, 510, 200, 42);

        guiltybutton.setBackground(new java.awt.Color(0, 0, 0));
        guiltybutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        guiltybutton.setForeground(new java.awt.Color(255, 255, 255));
        guiltybutton.setText("FIND GUILTY");
        guiltybutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guiltybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiltybuttonActionPerformed(evt);
            }
        });
        withagunpanel2.add(guiltybutton);
        guiltybutton.setBounds(640, 560, 200, 40);

        closebutton.setBackground(new java.awt.Color(0, 0, 0));
        closebutton.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        closebutton.setForeground(new java.awt.Color(255, 255, 255));
        closebutton.setText("Close Frame");
        closebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebuttonMouseClicked(evt);
            }
        });
        closebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebuttonActionPerformed(evt);
            }
        });
        withagunpanel2.add(closebutton);
        closebutton.setBounds(680, 650, 130, 30);

        jLabel79.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(153, 0, 0));
        jLabel79.setText("With a Gun");
        withagunpanel2.add(jLabel79);
        jLabel79.setBounds(10, 10, 140, 24);

        jLabel86.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(255, 255, 255));
        jLabel86.setText("Victim's Infos");
        withagunpanel2.add(jLabel86);
        jLabel86.setBounds(10, 40, 140, 21);

        jLabel80.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(255, 255, 255));
        jLabel80.setText("Name:");
        withagunpanel2.add(jLabel80);
        jLabel80.setBounds(10, 70, 88, 18);

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Surname:");
        withagunpanel2.add(jLabel10);
        jLabel10.setBounds(10, 110, 70, 18);

        jLabel81.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(255, 255, 255));
        jLabel81.setText("Gender:");
        withagunpanel2.add(jLabel81);
        jLabel81.setBounds(10, 150, 84, 18);

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Any fingerprint found?");
        withagunpanel2.add(jLabel11);
        jLabel11.setBounds(10, 270, 160, 18);

        jLabel84.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(255, 255, 255));
        jLabel84.setText("Was a crime weapon ");
        withagunpanel2.add(jLabel84);
        jLabel84.setBounds(10, 340, 140, 18);

        jLabel20.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("found at the crime scene?");
        withagunpanel2.add(jLabel20);
        jLabel20.setBounds(10, 360, 180, 15);

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Suspect's Infos");
        withagunpanel2.add(jLabel12);
        jLabel12.setBounds(310, 40, 170, 21);

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Suspect ID:");
        withagunpanel2.add(jLabel14);
        jLabel14.setBounds(310, 70, 81, 18);

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Name:");
        withagunpanel2.add(jLabel15);
        jLabel15.setBounds(310, 110, 60, 18);

        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Surname:");
        withagunpanel2.add(jLabel16);
        jLabel16.setBounds(310, 150, 90, 18);

        jLabel17.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Gender:");
        withagunpanel2.add(jLabel17);
        jLabel17.setBounds(310, 190, 70, 18);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Suspect ID:");
        withagunpanel2.add(jLabel3);
        jLabel3.setBounds(640, 100, 79, 25);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Victim's Name:");
        withagunpanel2.add(jLabel6);
        jLabel6.setBounds(640, 300, 100, 18);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifes/wallpaper1.png"))); // NOI18N
        withagunpanel2.add(jLabel1);
        jLabel1.setBounds(-170, 0, 1030, 730);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(withagunpanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(withagunpanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
     String suspect_id = susId2.getText();
     String sus_name = namesusfield2.getText();
     String sus_surname = sussurname.getText();
     String gender_sus = (String)gendersus2.getSelectedItem();
     String FMR ;
     String sus_phone = (String)gunsusnum.getText();
     String bloodSample;
     String bloodSamplee;
     String crimeGunSerialNum;
     String suspectGunSerialNum;
     String crimeBulletDiameter;
     String suspectBulletDiameter;
     String hormoneLevel = (String)drowcort2.getSelectedItem();
     susIdcomboBox.addItem(suspect_id);
     String[] logcalls = new String[5];
     String numberss = numbers.getText();
     logcalls = numberss.split(",");
     
     if(jRadioButton8.isSelected()){
         FMR = "Not Found";
     }
     else{
         FMR = (String)fpmr4.getSelectedItem();
     }
     
     if(jRadioButton11.isSelected()){
        crimeBulletDiameter = crimediameter.getText();
     }
     else{
        crimeBulletDiameter = "Not Found";
     }
     
     if(jRadioButton14.isSelected()){
         suspectBulletDiameter = susbulldia.getText();
     }
     else{
         suspectBulletDiameter = "None";
     }
     
     if(jRadioButton13.isSelected()){
         crimeGunSerialNum = "None";
     }
     else{
        crimeGunSerialNum = gunserialnumber.getText();
     }
     
     
     if(jRadioButton16.isSelected() || jRadioButton15.isSelected()){
         suspectGunSerialNum = "None";
     }
     else{
         suspectGunSerialNum = susserialnumber.getText();
     }
     
     
     
     if (drowsus2.isSelected() == true && drowalc2.isSelected() == false){
         bloodSample = "Drug found!!";
     }
     else if(drowalc2.isSelected() == true && drowsus2.isSelected() == false){
         bloodSample = "Alcohol has found!!";
      }
     else if(drowsus2.isSelected() == true && drowalc2.isSelected() == true){
         bloodSample = "Drug and Alcohol found!!";
     }
     else{
        bloodSample = "No foreign substance was found in the blood.";
     }
     
      if (drowsus2.isSelected() == true && drowalc2.isSelected() == false){
         bloodSamplee = "Drug";
     }
     else if(drowalc2.isSelected() == true && drowsus2.isSelected() == false){
         bloodSamplee = "Alcohol";
      }
     else if(drowsus2.isSelected() == true && drowalc2.isSelected() == true){
         bloodSamplee = "";
     }
     else{
        bloodSamplee = " ";
     }
      
      int rateBs = 0;
      int rateFp = 0;
      int rateHormone = 0;
      int ratePhone = 0;
      int rateCsn = 0;
      int totalRate=0;
      int rateCbd = 0;
      
      rateBs = WithAGunDeath.bloodSample(bloodSamplee);
      rateFp = WithAGunDeath.FingerprintRate(FMR);
      rateHormone = WithAGunDeath.hormoneLevel(hormoneLevel);
      ratePhone = WithAGunDeath.comparePhoneNum(sus_phone, logcalls);
      rateCbd = WithAGunDeath.compareBulletDiameter(crimeBulletDiameter, suspectBulletDiameter);
      rateCsn = WithAGunDeath.compareSerialNum(crimeGunSerialNum, suspectGunSerialNum);
      
      totalRate = rateBs+rateFp+rateCbd+rateHormone+rateCsn+ratePhone;
      
      WithAGunDeath w = new WithAGunDeath(suspect_id,sus_name,sus_surname,gender_sus,FMR,suspectGunSerialNum,
              suspectBulletDiameter,hormoneLevel, bloodSample,sus_phone,totalRate);
              
    InfoClass.addSuspect(w);
    jTextField3.setText("Suspect added!!");
     
     
    }//GEN-LAST:event_addbuttonActionPerformed

    private void guiltybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiltybuttonActionPerformed
        FindGuilty fg = new FindGuilty();
        fg.setVisible(true);
        
        Crime guilty = InfoClass.findGuilty();
       
        fg.jTextArea1.append("The max rate is: " + InfoClass.findGuilty().getTotalGuiltyRate()+ ".\nThe max rate is belongs to: "+ guilty.getSuspectId()+
               "\n\nHERE IS THE GUILTY'S INFOS: \n"+ guilty.toString());
    }//GEN-LAST:event_guiltybuttonActionPerformed

    private void closebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebuttonMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_closebuttonMouseClicked

    private void displaybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displaybuttonActionPerformed
       DisplayInfos ds = new DisplayInfos();
       ds.setVisible(true);
       
       if(InfoClass.suspectList.isEmpty()){
         ds.jTextArea1.append("\nThere are no suspect in the system");
        }
        else{
        ds.jTextArea1.append(InfoClass.getAllSuspect());
        ds.jTextArea3.setText(InfoClass.getAllVictim());
       }
    }//GEN-LAST:event_displaybuttonActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
        SearchSuspect ss = new SearchSuspect();
        ss.setVisible(true);
        
        if(InfoClass.suspectList.isEmpty()){
         ss.jTextArea1.append("\nThere are no suspect in the system");
        }
        else{
         String suspectId = (String)susIdcomboBox.getSelectedItem();
         Crime cd = InfoClass.searchSuspect(suspectId);
          if(cd == null)
                ss.jTextArea1.append("\nSuspect with the id " + suspectId + " is not found");        
            else
                ss.jTextArea1.append(cd.toString());
        }

    }//GEN-LAST:event_searchbuttonActionPerformed

    private void addvicbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addvicbuttonActionPerformed
    String vic_name = (String)namevicfield4.getText();
    String vic_surname = (String)surnamevic.getText();
    String gender_vic = (String)gendervic4.getSelectedItem();
    String crimeBulletDiameter;
    String crimeGunSerialNum;
    String[] logcalls = new String[5];
    String numberss = numbers.getText();
    logcalls = numberss.split(",");
    
     if(jRadioButton11.isSelected()){
        crimeBulletDiameter = crimediameter.getText();
     }
     else{
        crimeBulletDiameter = "Not Found";
     }
     
      if(jRadioButton13.isSelected()){
         crimeGunSerialNum = "None";
     }
     else{
        crimeGunSerialNum = gunserialnumber.getText();
     }
      if(jRadioButton10.isSelected()){
          crimeGunSerialNum = "Not Found";
      }
      else{
          crimeGunSerialNum = gunserialnumber.getText();
      }
      
    
    
    WithAGunDeath v = new WithAGunDeath(vic_name,vic_surname,gender_vic,logcalls,crimeGunSerialNum,crimeBulletDiameter);
    InfoClass.addVictim(v);
    jTextField3.setText("Victim added!");
    
    }//GEN-LAST:event_addvicbuttonActionPerformed

    private void deletevictimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletevictimActionPerformed
     DisplayInfos ds = new DisplayInfos();
     ds.setVisible(true);
     
     InfoClass.deleteVictim(vicdelname.getText());
     
     ds.jTextArea3.setText("You deleted the victim.\nThere are no victims in the system."+InfoClass.getAllVictim());
     ds.jTextArea1.append(InfoClass.getAllSuspect());
    }//GEN-LAST:event_deletevictimActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        DisplayInfos ds = new DisplayInfos();
        ds.setVisible(true);
        
            InfoClass.deleteSuspect((String)susIdcomboBox.getSelectedItem());
            susIdcomboBox.removeItem(susIdcomboBox.getSelectedItem());
            
            ds.jTextArea3.append(InfoClass.getAllVictim());
            ds.jTextArea1.append("The id you selected has been deleted\n\n"+
                    "Here is the remaining suspects\n" +InfoClass.getAllSuspect());
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        serialNum1.setVisible(true);
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        jPanel2.setVisible(true);
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    private void jRadioButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton14ActionPerformed
       serialNum2.setVisible(true);
       jPanel3.setVisible(true);
    }//GEN-LAST:event_jRadioButton14ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        fppanel3.setVisible(true);
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        fppanel3.setVisible(false);
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton15ActionPerformed
       serialNum2.setVisible(false);
       jPanel3.setVisible(false);
    }//GEN-LAST:event_jRadioButton15ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        serialNum1.setVisible(false);
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        jPanel2.setVisible(false);
    }//GEN-LAST:event_jRadioButton12ActionPerformed

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        susId2.setText("");
        namesusfield2.setText("");
        sussurname.setText("");
        gendersus2.setSelectedItem(null);
        fpmr4.setSelectedItem(null);
        gunsusnum.setText("");
        drowcort2.setSelectedItem(null);
        drowsus2.setSelected(false);
        drowalc2.setSelected(false);
        buttonGroup4.clearSelection();
        susbulldia.setText("");
        jRadioButton16.setSelected(false);
        susserialnumber.setText("");
    }//GEN-LAST:event_clearbuttonActionPerformed

    private void fpmr4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fpmr4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fpmr4ActionPerformed

    private void numbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numbersActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int result = JOptionPane.showConfirmDialog(null,
            "Are you sure you want to exit the program ?\nIf you exit the program, your progress will be lost.", "Exit Confirmation: ",
            JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION)
          setDefaultCloseOperation(DrowningFrame.EXIT_ON_CLOSE);
        else if (result == JOptionPane.NO_OPTION)
          setDefaultCloseOperation(DrowningFrame.DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void closebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private javax.swing.JButton addvicbutton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton clearbutton;
    private javax.swing.JButton closebutton;
    private javax.swing.JTextField crimediameter;
    private javax.swing.JButton deletebutton;
    private javax.swing.JButton deletevictim;
    private javax.swing.JButton displaybutton;
    private javax.swing.JCheckBox drowalc2;
    private javax.swing.JComboBox<String> drowcort2;
    private javax.swing.JCheckBox drowsus2;
    private javax.swing.JComboBox<String> fpmr4;
    private javax.swing.JPanel fppanel3;
    private javax.swing.JComboBox<String> gendersus2;
    private javax.swing.JComboBox<String> gendervic4;
    private javax.swing.JButton guiltybutton;
    private javax.swing.JTextField gunserialnumber;
    private javax.swing.JTextField gunsusnum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField namesusfield2;
    private javax.swing.JTextField namevicfield4;
    private javax.swing.JTextField numbers;
    private javax.swing.JButton searchbutton;
    private javax.swing.JPanel serialNum1;
    private javax.swing.JPanel serialNum2;
    private javax.swing.JTextField surnamevic;
    private javax.swing.JTextField susId2;
    private javax.swing.JComboBox<String> susIdcomboBox;
    private javax.swing.JTextField susbulldia;
    private javax.swing.JTextField susserialnumber;
    private javax.swing.JTextField sussurname;
    private javax.swing.JTextField vicdelname;
    private javax.swing.JPanel withagunpanel2;
    // End of variables declaration//GEN-END:variables
}
